var searchData=
[
  ['fail_0',['fail',['../double__tap_8h.html#a308dd8033c0186d3e5b5520a1481d4c4',1,'double_tap.h']]],
  ['fallback_1',['fallback',['../md_docs_2internals.html#autotoc_md172',1,'3.3 macOS JIT Hardening and the Entitlement Fallback'],['../md_docs_2internals.html#autotoc_md174',1,'The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback']]],
  ['features_2',['features',['..//home/runner/work/infix/infix/docs/doxygen-awesome-css/README.md#autotoc_md146',1,'Features'],['../index.html#autotoc_md2',1,'Key Features']]],
  ['features_20deep_20dive_3',['3. Security Features Deep Dive',['../md_docs_2internals.html#autotoc_md169',1,'']]],
  ['fetchcontent_4',['CMake with FetchContent',['..//home/runner/work/infix/infix/docs/doxygen-awesome-css/README.md#autotoc_md150',1,'']]],
  ['ffi_20calls_5',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_docs_2cookbook.html#autotoc_md65',1,'']]],
  ['ffi_20cookbook_6',['The &lt;tt&gt;infix&lt;/tt&gt; FFI Cookbook',['../md_docs_2cookbook.html',1,'']]],
  ['ffi_20library_20for_20c_7',['infix: A JIT-Powered FFI Library for C',['../index.html',1,'']]],
  ['first_20signature_20system_8',['1.3 Our Solution: A Human-First Signature System',['../md_docs_2signatures.html#autotoc_md195',1,'']]],
  ['fixed_20size_20arrays_9',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md51',1,'']]],
  ['fixed_20width_20types_20recommended_10',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md199',1,'']]],
  ['for_11',['Who is this for?',['../index.html#autotoc_md1',1,'']]],
  ['for_20a_20group_20of_20types_12',['Recipe: Using a Custom Arena for a Group of Types',['../md_docs_2cookbook.html#autotoc_md94',1,'']]],
  ['for_20a_20wrapper_13',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_docs_2cookbook.html#autotoc_md90',1,'']]],
  ['for_20c_14',['infix: A JIT-Powered FFI Library for C',['../index.html',1,'']]],
  ['for_20callbacks_15',['Universal Context for Callbacks',['../md_docs_2internals.html#autotoc_md164',1,'']]],
  ['for_20data_20marshalling_16',['Chapter 7: Introspection for Data Marshalling',['../md_docs_2cookbook.html#autotoc_md87',1,'']]],
  ['for_20dynamic_20data_20marshalling_17',['Powerful Introspection for Dynamic Data Marshalling',['../index.html#autotoc_md16',1,'']]],
  ['for_20other_20compiled_20languages_18',['The Pattern for Other Compiled Languages',['../md_docs_2cookbook.html#autotoc_md72',1,'']]],
  ['for_20tt_20qsort_20tt_19',['Recipe: Creating a Stateless Callback for &lt;tt&gt;qsort&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md57',1,'']]],
  ['formatting_20tables_20',['Formatting Tables',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html#tricks-tables',1,'']]],
  ['fortran_21',['Fortran',['../md_docs_2cookbook.html#autotoc_md78',1,'']]],
  ['forward_20call_20calling_20c_20from_20your_20code_22',['Forward Call (Calling C from your code)',['../index.html#autotoc_md11',1,'']]],
  ['forward_20calls_23',['Chapter 1: The Basics (Forward Calls)',['../md_docs_2cookbook.html#autotoc_md38',1,'']]],
  ['four_20pillars_20of_20a_20language_20binding_24',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md118',1,'']]],
  ['fragment_20copy_20button_25',['Fragment Copy Button',['../md_docs_2doxygen-awesome-css_2docs_2extensions.html#extension-copy-button',1,'']]],
  ['from_20a_20function_26',['Recipe: Receiving a Struct from a Function',['../md_docs_2cookbook.html#autotoc_md46',1,'']]],
  ['from_20a_20shared_20library_27',['Reading Global Variables from a Shared Library',['../index.html#autotoc_md14',1,'']]],
  ['from_20a_20struct_20v_20table_20emulation_28',['Recipe: Calling a Function Pointer from a Struct (V-Table Emulation)',['../md_docs_2cookbook.html#autotoc_md63',1,'']]],
  ['from_20tt_20dyncall_20tt_20to_20tt_20infix_20tt_29',['Recipe: Porting a Python Binding from &lt;tt&gt;dyncall&lt;/tt&gt; to &lt;tt&gt;infix&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md119',1,'']]],
  ['from_20your_20code_30',['Forward Call (Calling C from your code)',['../index.html#autotoc_md11',1,'']]],
  ['full_20width_31',['Full Width',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html#autotoc_md141',1,'']]],
  ['func_5fptr_5finfo_32',['func_ptr_info',['../structinfix__type__t.html#a2a2d9a8c127bba88a5da75433005bdfb',1,'infix_type_t']]],
  ['function_33',['function',['../md_docs_2cookbook.html#autotoc_md39',1,'Recipe: Calling a Simple C Function'],['../md_docs_2cookbook.html#autotoc_md46',1,'Recipe: Receiving a Struct from a Function'],['../md_docs_2cookbook.html#autotoc_md103',1,'Scenario 1: Calling a Simple Function']]],
  ['function_20pointer_34',['Recipe: Receiving and Calling a Function Pointer',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['function_20pointer_20from_20a_20struct_20v_20table_20emulation_35',['Recipe: Calling a Function Pointer from a Struct (V-Table Emulation)',['../md_docs_2cookbook.html#autotoc_md63',1,'']]],
  ['function_20pointer_20syntax_36',['Pitfall: Function Pointer Syntax',['../md_docs_2cookbook.html#autotoc_md100',1,'']]],
  ['function_20with_20a_20struct_37',['Scenario 2: Calling a Function with a Struct',['../md_docs_2cookbook.html#autotoc_md107',1,'']]],
  ['functions_20like_20tt_20printf_20tt_38',['Recipe: Calling Variadic Functions like &lt;tt&gt;printf&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['further_20installation_20instructions_39',['Further installation instructions',['..//home/runner/work/infix/infix/docs/doxygen-awesome-css/README.md#autotoc_md154',1,'']]],
  ['fuzz_20testing_40',['3.4 Fuzz Testing',['../md_docs_2internals.html#autotoc_md175',1,'']]]
];
