var searchData=
[
  ['w_20x_0',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md143',1,'']]],
  ['w_20x_20write_20xor_20execute_20memory_20policy_1',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md252',1,'']]],
  ['whitespace_20and_20comments_2',['4.1 Whitespace and Comments',['../md_docs_2signatures.html#autotoc_md181',1,'']]],
  ['who_20is_20this_20for_3',['Who is this for?',['../md_README.html#autotoc_md214',1,'']]],
  ['why_20this_20syntax_4',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md183',1,'']]],
  ['wide_5',['System-wide',['../md_docs_2api_2html_2README.html#autotoc_md47',1,'']]],
  ['width_6',['width',['../md_docs_2api_2html_2docs_2tricks.html#tricks-sidebar',1,'Choosing Sidebar Width'],['../md_docs_2api_2html_2docs_2tricks.html#autotoc_md36',1,'Full Width']]],
  ['width_20types_20recommended_7',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md172',1,'']]],
  ['win32_5fmsgbox_2ec_8',['win32_msgbox.c',['../win32__msgbox_8c.html',1,'']]],
  ['windows_20with_20msvc_9',['NMake (Windows with MSVC)',['../md_INSTALL.html#autotoc_md200',1,'']]],
  ['with_20a_20c_20class_20directly_10',['Recipe: Interfacing with a C++ Class (Directly)',['../md_docs_2cookbook.html#autotoc_md81',1,'']]],
  ['with_20a_20struct_11',['Scenario 2: Calling a Function with a Struct',['../md_docs_2cookbook.html#autotoc_md117',1,'']]],
  ['with_20c_20templates_12',['Recipe: Interfacing with C++ Templates',['../md_docs_2cookbook.html#autotoc_md82',1,'']]],
  ['with_20complex_20numbers_13',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md67',1,'']]],
  ['with_20fetchcontent_14',['CMake with FetchContent',['../md_docs_2api_2html_2README.html#autotoc_md45',1,'']]],
  ['with_20fixed_20size_20arrays_15',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md66',1,'']]],
  ['with_20gdb_20lldb_16',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md154',1,'']]],
  ['with_20graceful_20fallback_17',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md147',1,'']]],
  ['with_20graphviz_18',['Diagrams with Graphviz',['../md_docs_2api_2html_2docs_2tricks.html#tricks-graphviz',1,'']]],
  ['with_20msvc_19',['NMake (Windows with MSVC)',['../md_INSTALL.html#autotoc_md200',1,'']]],
  ['with_20nested_20ffi_20calls_20',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_docs_2cookbook.html#autotoc_md77',1,'']]],
  ['with_20opaque_20pointers_20incomplete_20types_21',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md58',1,'']]],
  ['with_20other_20languages_22',['Chapter 5: Interoperability with Other Languages',['../md_docs_2cookbook.html#autotoc_md79',1,'']]],
  ['with_20other_20systems_23',['4.4 Comparison with Other Systems',['../md_docs_2signatures.html#autotoc_md184',1,'']]],
  ['with_20packed_20structs_24',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md64',1,'']]],
  ['with_20simd_20vectors_25',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md68',1,'']]],
  ['with_20the_20signature_20parser_26',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md100',1,'']]],
  ['with_20tt_20find_5fpackage_20tt_27',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md_INSTALL.html#autotoc_md204',1,'']]],
  ['with_20tt_20infix_5fdump_5fhex_20tt_28',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_docs_2internals.html#autotoc_md153',1,'']]],
  ['with_20unions_29',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md65',1,'']]],
  ['without_20linking_30',['Recipe: Calling Native System Libraries without Linking',['../md_docs_2cookbook.html#autotoc_md93',1,'']]],
  ['working_20with_20complex_20numbers_31',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md67',1,'']]],
  ['working_20with_20fixed_20size_20arrays_32',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md66',1,'']]],
  ['working_20with_20opaque_20pointers_20incomplete_20types_33',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md58',1,'']]],
  ['working_20with_20packed_20structs_34',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md64',1,'']]],
  ['working_20with_20simd_20vectors_35',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md68',1,'']]],
  ['working_20with_20unions_36',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md65',1,'']]],
  ['wrapper_37',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_docs_2cookbook.html#autotoc_md101',1,'']]],
  ['write_20xor_20execute_20memory_20policy_38',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md252',1,'']]],
  ['write_20xor_20execute_20w_20x_39',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md143',1,'']]],
  ['writing_20global_20variables_40',['Recipe: Reading and Writing Global Variables',['../md_docs_2cookbook.html#autotoc_md94',1,'']]]
];
