var searchData=
[
  ['w_20x_0',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md170',1,'']]],
  ['whitespace_20and_20comments_1',['4.1 Whitespace and Comments',['../md_docs_2signatures.html#autotoc_md208',1,'']]],
  ['who_20is_20this_20for_2',['Who is this for?',['../index.html#autotoc_md1',1,'']]],
  ['why_20this_20syntax_3',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md210',1,'']]],
  ['wide_4',['System-wide',['..//home/runner/work/infix/infix/docs/doxygen-awesome-css/README.md#autotoc_md152',1,'']]],
  ['width_5',['width',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html#tricks-sidebar',1,'Choosing Sidebar Width'],['../md_docs_2doxygen-awesome-css_2docs_2tricks.html#autotoc_md141',1,'Full Width']]],
  ['width_20types_20recommended_6',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md199',1,'']]],
  ['with_20a_20c_20class_20directly_7',['Recipe: Interfacing with a C++ Class (Directly)',['../md_docs_2cookbook.html#autotoc_md70',1,'']]],
  ['with_20a_20struct_8',['Scenario 2: Calling a Function with a Struct',['../md_docs_2cookbook.html#autotoc_md107',1,'']]],
  ['with_20c_20templates_9',['Recipe: Interfacing with C++ Templates',['../md_docs_2cookbook.html#autotoc_md71',1,'']]],
  ['with_20complex_20numbers_10',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md52',1,'']]],
  ['with_20enums_20strong_11',['&lt;strong&gt;Recipe: Working with Enums&lt;/strong&gt;',['../md_docs_2cookbook.html#autotoc_md54',1,'']]],
  ['with_20fetchcontent_12',['CMake with FetchContent',['..//home/runner/work/infix/infix/docs/doxygen-awesome-css/README.md#autotoc_md150',1,'']]],
  ['with_20fixed_20size_20arrays_13',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md51',1,'']]],
  ['with_20gdb_20lldb_14',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md181',1,'']]],
  ['with_20graceful_20fallback_15',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md174',1,'']]],
  ['with_20graphviz_16',['Diagrams with Graphviz',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html#tricks-graphviz',1,'']]],
  ['with_20nested_20ffi_20calls_17',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_docs_2cookbook.html#autotoc_md65',1,'']]],
  ['with_20opaque_20pointers_20incomplete_20types_18',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md42',1,'']]],
  ['with_20other_20languages_19',['Chapter 5: Interoperability with Other Languages',['../md_docs_2cookbook.html#autotoc_md68',1,'']]],
  ['with_20other_20systems_20',['4.4 Comparison with Other Systems',['../md_docs_2signatures.html#autotoc_md211',1,'']]],
  ['with_20out_20parameters_21',['Recipe: Working with &quot;Out&quot; Parameters',['../md_docs_2cookbook.html#autotoc_md41',1,'']]],
  ['with_20packed_20structs_22',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md48',1,'']]],
  ['with_20simd_20vectors_23',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md53',1,'']]],
  ['with_20structs_20that_20contain_20bitfields_24',['Recipe: Working with Structs that Contain Bitfields',['../md_docs_2cookbook.html#autotoc_md49',1,'']]],
  ['with_20the_20signature_20parser_25',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md88',1,'']]],
  ['with_20tt_20infix_5fdump_5fhex_20tt_26',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_docs_2internals.html#autotoc_md180',1,'']]],
  ['with_20unions_27',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md50',1,'']]],
  ['without_20linking_28',['Recipe: Calling Native System Libraries without Linking',['../md_docs_2cookbook.html#autotoc_md81',1,'']]],
  ['working_20with_20complex_20numbers_29',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md52',1,'']]],
  ['working_20with_20enums_20strong_30',['&lt;strong&gt;Recipe: Working with Enums&lt;/strong&gt;',['../md_docs_2cookbook.html#autotoc_md54',1,'']]],
  ['working_20with_20fixed_20size_20arrays_31',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md51',1,'']]],
  ['working_20with_20opaque_20pointers_20incomplete_20types_32',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md42',1,'']]],
  ['working_20with_20out_20parameters_33',['Recipe: Working with &quot;Out&quot; Parameters',['../md_docs_2cookbook.html#autotoc_md41',1,'']]],
  ['working_20with_20packed_20structs_34',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md48',1,'']]],
  ['working_20with_20simd_20vectors_35',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md53',1,'']]],
  ['working_20with_20structs_20that_20contain_20bitfields_36',['Recipe: Working with Structs that Contain Bitfields',['../md_docs_2cookbook.html#autotoc_md49',1,'']]],
  ['working_20with_20unions_37',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md50',1,'']]],
  ['wrapper_38',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_docs_2cookbook.html#autotoc_md90',1,'']]],
  ['write_20xor_20execute_20w_20x_39',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md170',1,'']]],
  ['writing_20global_20variables_40',['Recipe: Reading and Writing Global Variables',['../md_docs_2cookbook.html#autotoc_md82',1,'']]]
];
