var searchData=
[
  ['table_20emulation_0',['Recipe: Calling a Function Pointer from a Struct (V-Table Emulation)',['../md_docs_2cookbook.html#autotoc_md63',1,'']]],
  ['table_20of_20contents_1',['Table of Contents',['../md_docs_2cookbook.html#autotoc_md36',1,'']]],
  ['takeaways_2',['Analysis and Takeaways',['../md_docs_2cookbook.html#autotoc_md115',1,'']]],
  ['target_5ffn_3',['target_fn',['../structinfix__forward__t.html#a3af1080ceceea1dc05bee200422c60d8',1,'infix_forward_t::target_fn'],['../structinfix__call__frame__layout.html#a5eaab27cc161e119694a4508341acf20',1,'infix_call_frame_layout::target_fn']]],
  ['technical_20specification_4',['Part 4: Technical Specification',['../md_docs_2signatures.html#autotoc_md169',1,'']]],
  ['techniques_5',['Chapter 4: Advanced Techniques',['../md_docs_2cookbook.html#autotoc_md60',1,'']]],
  ['templates_6',['Recipe: Interfacing with C++ Templates',['../md_docs_2cookbook.html#autotoc_md71',1,'']]],
  ['test_7',['TEST',['../double__tap_8h.html#ab946e2e7f7679350627acfded8e2658b',1,'double_tap.h']]],
  ['testing_8',['testing',['../md_docs_2internals.html#autotoc_md138',1,'3.4 Fuzz Testing'],['../md_docs_2porting.html#autotoc_md152',1,'Step 5: Testing']]],
  ['that_20contain_20bitfields_9',['Recipe: Working with Structs that Contain Bitfields',['../md_docs_2cookbook.html#autotoc_md49',1,'']]],
  ['the_20abi_20specification_10',['Step 2: Implement the ABI Specification',['../md_docs_2porting.html#autotoc_md149',1,'']]],
  ['the_20basics_20forward_20calls_11',['Chapter 1: The Basics (Forward Calls)',['../md_docs_2cookbook.html#autotoc_md38',1,'']]],
  ['the_20challenge_20of_20interoperability_12',['1.1 The Challenge of Interoperability',['../md_docs_2signatures.html#autotoc_md155',1,'']]],
  ['the_20challenge_3a_20hardened_20runtimes_20on_20apple_20silicon_13',['The Challenge: Hardened Runtimes on Apple Silicon',['../md_docs_2internals.html#autotoc_md136',1,'']]],
  ['the_20entitlement_20fallback_14',['3.3 macOS JIT Hardening and the Entitlement Fallback',['../md_docs_2internals.html#autotoc_md135',1,'']]],
  ['the_20four_20pillars_20of_20a_20language_20binding_15',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md118',1,'']]],
  ['the_20infix_20signature_20and_20type_20system_16',['The infix Signature and Type System',['../md_docs_2signatures.html',1,'']]],
  ['the_20instruction_20emitters_17',['Step 3: Implement the Instruction Emitters',['../md_docs_2porting.html#autotoc_md150',1,'']]],
  ['the_20library_18',['Building the Library',['../index.html#autotoc_md5',1,'']]],
  ['the_20limitations_20of_20c_20declarations_19',['1.2 The Limitations of C Declarations',['../md_docs_2signatures.html#autotoc_md156',1,'']]],
  ['the_20manual_20c_20api_20advanced_20',['Part 3: The Manual C API (Advanced)',['../index.html#autotoc_md15',1,'']]],
  ['the_20named_20type_20registry_21',['the named type registry',['../md_docs_2signatures.html#autotoc_md165',1,'Part 3: The Named Type Registry'],['../index.html#autotoc_md13',1,'Using the Named Type Registry']]],
  ['the_20new_20abi_22',['Step 4: Integrate the New ABI',['../md_docs_2porting.html#autotoc_md151',1,'']]],
  ['the_20pattern_20for_20other_20compiled_20languages_23',['The Pattern for Other Compiled Languages',['../md_docs_2cookbook.html#autotoc_md72',1,'']]],
  ['the_20power_20of_20callbacks_20reverse_20calls_24',['Chapter 3: The Power of Callbacks (Reverse Calls)',['../md_docs_2cookbook.html#autotoc_md56',1,'']]],
  ['the_20self_20contained_20object_20model_25',['The Self-Contained Object Model',['../md_docs_2internals.html#autotoc_md125',1,'']]],
  ['the_20signature_20language_26',['Part 1: The Signature Language',['../index.html#autotoc_md9',1,'']]],
  ['the_20signature_20language_20reference_27',['Part 2: The Signature Language Reference',['../md_docs_2signatures.html#autotoc_md158',1,'']]],
  ['the_20signature_20parser_28',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md88',1,'']]],
  ['the_20trampoline_20generation_20pipeline_29',['The Trampoline Generation Pipeline',['../md_docs_2internals.html#autotoc_md130',1,'']]],
  ['the_20tt_20dyncall_20tt_20approach_30',['the tt dyncall tt approach',['../md_docs_2cookbook.html#autotoc_md104',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md112',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md108',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach']]],
  ['the_20tt_20infix_20tt_20approach_31',['the tt infix tt approach',['../md_docs_2cookbook.html#autotoc_md106',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md114',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md110',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach']]],
  ['the_20tt_20infix_20tt_20ffi_20cookbook_32',['The &lt;tt&gt;infix&lt;/tt&gt; FFI Cookbook',['../md_docs_2cookbook.html',1,'']]],
  ['the_20tt_20infix_20tt_20solution_3a_20runtime_20detection_20with_20graceful_20fallback_33',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md137',1,'']]],
  ['the_20tt_20libffi_20tt_20approach_34',['the tt libffi tt approach',['../md_docs_2cookbook.html#autotoc_md105',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md113',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md109',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach']]],
  ['the_20unity_20build_35',['The Unity Build',['../md_docs_2internals.html#autotoc_md124',1,'']]],
  ['the_20universal_20principle_3a_20the_20c_20abi_36',['The Universal Principle: The C ABI',['../md_docs_2cookbook.html#autotoc_md69',1,'']]],
  ['this_20for_37',['Who is this for?',['../index.html#autotoc_md1',1,'']]],
  ['this_20syntax_38',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md172',1,'']]],
  ['thread_20safety_20strong_39',['&lt;strong&gt;Recipe: Proving Thread Safety&lt;/strong&gt;',['../md_docs_2cookbook.html#autotoc_md66',1,'']]],
  ['tier_201_3a_20abstract_20c_20types_40',['Tier 1: Abstract C Types',['../md_docs_2signatures.html#autotoc_md160',1,'']]],
  ['tier_202_3a_20explicit_20fixed_20width_20types_20recommended_41',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md161',1,'']]],
  ['to_20a_20new_20platform_42',['Porting &lt;tt&gt;infix&lt;/tt&gt; to a New Platform',['../md_docs_2porting.html',1,'']]],
  ['to_20tt_20infix_20tt_43',['Recipe: Porting a Python Binding from &lt;tt&gt;dyncall&lt;/tt&gt; to &lt;tt&gt;infix&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md119',1,'']]],
  ['todo_44',['TODO',['../double__tap_8h.html#a9c9971e17638fc67630c02c7759c6d2f',1,'double_tap.h']]],
  ['tools_45',['Useful Tools',['../md_docs_2internals.html#autotoc_md145',1,'']]],
  ['total_5fstack_5falloc_46',['total_stack_alloc',['../structinfix__reverse__call__frame__layout.html#aedb51aeb6365d359bcb27d1e9920a0d8',1,'infix_reverse_call_frame_layout::total_stack_alloc'],['../structinfix__call__frame__layout.html#a743d543342256cf155458951d48c613e',1,'infix_call_frame_layout::total_stack_alloc']]],
  ['trampoline_20for_20a_20wrapper_47',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_docs_2cookbook.html#autotoc_md90',1,'']]],
  ['trampoline_20generation_20pipeline_48',['The Trampoline Generation Pipeline',['../md_docs_2internals.html#autotoc_md130',1,'']]],
  ['trampoline_2ec_49',['trampoline.c',['../trampoline_8c.html',1,'']]],
  ['trampolines_50',['Best Practice: Caching Trampolines',['../md_docs_2cookbook.html#autotoc_md93',1,'']]],
  ['troubleshooting_51',['Chapter 9: Common Pitfalls &amp; Troubleshooting',['../md_docs_2cookbook.html#autotoc_md97',1,'']]],
  ['tt_20args_20tt_52',['Mistake: Passing a Value Instead of a Pointer in &lt;tt&gt;args[]&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md98',1,'']]],
  ['tt_20dyncall_20tt_20approach_53',['tt dyncall tt approach',['../md_docs_2cookbook.html#autotoc_md104',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md108',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md112',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach']]],
  ['tt_20dyncall_20tt_20to_20tt_20infix_20tt_54',['Recipe: Porting a Python Binding from &lt;tt&gt;dyncall&lt;/tt&gt; to &lt;tt&gt;infix&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md119',1,'']]],
  ['tt_20error_5fapi_20tt_55',['Error Handling API (&lt;tt&gt;error_api&lt;/tt&gt;)',['../index.html#autotoc_md26',1,'']]],
  ['tt_20exports_5fapi_20tt_56',['Dynamic Library &amp; Globals API (&lt;tt&gt;exports_api&lt;/tt&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['tt_20high_5flevel_5fapi_20tt_57',['High-Level Signature API (&lt;tt&gt;high_level_api&lt;/tt&gt;)',['../index.html#autotoc_md20',1,'']]],
  ['tt_20infix_20tt_20approach_58',['tt infix tt approach',['../md_docs_2cookbook.html#autotoc_md106',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md110',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md114',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach']]],
  ['tt_20infix_20tt_20ffi_20cookbook_59',['The &lt;tt&gt;infix&lt;/tt&gt; FFI Cookbook',['../md_docs_2cookbook.html',1,'']]],
  ['tt_20infix_20tt_20signature_20mismatch_60',['Mistake: &lt;tt&gt;infix&lt;/tt&gt; Signature Mismatch',['../md_docs_2cookbook.html#autotoc_md99',1,'']]],
  ['tt_20infix_20tt_20solution_3a_20runtime_20detection_20with_20graceful_20fallback_61',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md137',1,'']]],
  ['tt_20infix_20tt_20to_20a_20new_20platform_62',['Porting &lt;tt&gt;infix&lt;/tt&gt; to a New Platform',['../md_docs_2porting.html',1,'']]],
  ['tt_20infix_20tt_20vs_20tt_20libffi_20tt_20and_20tt_20dyncall_20tt_63',['Chapter 10: A Comparative Look: &lt;tt&gt;infix&lt;/tt&gt; vs. &lt;tt&gt;libffi&lt;/tt&gt; and &lt;tt&gt;dyncall&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md102',1,'']]],
  ['tt_20infix_5fdump_5fhex_20tt_64',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_docs_2internals.html#autotoc_md143',1,'']]],
  ['tt_20infix_5fregister_5ftypes_20tt_65',['Defining Types (&lt;tt&gt;infix_register_types&lt;/tt&gt;)',['../md_docs_2signatures.html#autotoc_md166',1,'']]],
  ['tt_20introspection_5fapi_20tt_66',['Introspection API (&lt;tt&gt;introspection_api&lt;/tt&gt;)',['../index.html#autotoc_md25',1,'']]],
  ['tt_20libffi_20tt_20approach_67',['tt libffi tt approach',['../md_docs_2cookbook.html#autotoc_md113',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md105',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md109',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach']]],
  ['tt_20long_20double_20tt_20strong_68',['&lt;strong&gt;Recipe: Handling &lt;tt&gt;long double&lt;/tt&gt;&lt;/strong&gt;',['../md_docs_2cookbook.html#autotoc_md64',1,'']]],
  ['tt_20manual_5fapi_20tt_69',['Manual API (&lt;tt&gt;manual_api&lt;/tt&gt;)',['../index.html#autotoc_md22',1,'']]],
  ['tt_20memory_5fmanagement_20tt_70',['Memory Management (&lt;tt&gt;memory_management&lt;/tt&gt;)',['../index.html#autotoc_md24',1,'']]],
  ['tt_20printf_20tt_71',['Recipe: Calling Variadic Functions like &lt;tt&gt;printf&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['tt_20qsort_20tt_72',['Recipe: Creating a Stateless Callback for &lt;tt&gt;qsort&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md57',1,'']]],
  ['tt_20registry_5fapi_20tt_73',['Named Type Registry (&lt;tt&gt;registry_api&lt;/tt&gt;)',['../index.html#autotoc_md19',1,'']]],
  ['tt_20src_20common_20infix_5fconfig_20h_20tt_74',['Step 1: Platform Detection (&lt;tt&gt;src/common/infix_config.h&lt;/tt&gt;)',['../md_docs_2porting.html#autotoc_md148',1,'']]],
  ['tt_20type_5fsystem_20tt_75',['Type System (&lt;tt&gt;type_system&lt;/tt&gt;)',['../index.html#autotoc_md23',1,'']]],
  ['type_76',['type',['../struct__infix__registry__entry__t.html#a5337bf58d6fcd7fa8b08a9ac483c6702',1,'_infix_registry_entry_t::type'],['../structinfix__arg__location.html#a4f53bb713bc5749863d8ba2633b74604',1,'infix_arg_location::type'],['../structinfix__struct__member__t.html#aa89e6621da98f5115dcc807599c4ac77',1,'infix_struct_member_t::type'],['../structinfix__function__argument__t.html#a1bd256c75cb6ec767cec121370e6a0ed',1,'infix_function_argument_t::type']]],
  ['type_20constructors_20and_20composite_20structures_77',['2.2 Type Constructors and Composite Structures',['../md_docs_2signatures.html#autotoc_md162',1,'']]],
  ['type_20creation_20api_78',['Manual Type-Creation API',['../group__manual__api.html',1,'']]],
  ['type_20registry_79',['type registry',['../md_docs_2signatures.html#autotoc_md165',1,'Part 3: The Named Type Registry'],['../index.html#autotoc_md13',1,'Using the Named Type Registry']]],
  ['type_20registry_20api_80',['Named Type Registry API',['../group__registry__api.html',1,'']]],
  ['type_20registry_20tt_20registry_5fapi_20tt_81',['Named Type Registry (&lt;tt&gt;registry_api&lt;/tt&gt;)',['../index.html#autotoc_md19',1,'']]],
  ['type_20system_82',['type system',['../md_docs_2signatures.html',1,'The infix Signature and Type System'],['../group__type__system.html',1,'Type System']]],
  ['type_20system_20tt_20type_5fsystem_20tt_83',['Type System (&lt;tt&gt;type_system&lt;/tt&gt;)',['../index.html#autotoc_md23',1,'']]],
  ['type_5fregistry_2ec_84',['type_registry.c',['../type__registry_8c.html',1,'']]],
  ['type_5fsystem_20tt_85',['Type System (&lt;tt&gt;type_system&lt;/tt&gt;)',['../index.html#autotoc_md23',1,'']]],
  ['types_86',['types',['../md_docs_2cookbook.html#autotoc_md94',1,'Recipe: Using a Custom Arena for a Group of Types'],['../md_docs_2cookbook.html#autotoc_md42',1,'Recipe: Working with Opaque Pointers (Incomplete Types)'],['../md_docs_2signatures.html#autotoc_md160',1,'Tier 1: Abstract C Types'],['../md_docs_2signatures.html#autotoc_md167',1,'Using Named Types']]],
  ['types_20recommended_87',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md161',1,'']]],
  ['types_20tt_20infix_5fregister_5ftypes_20tt_88',['Defining Types (&lt;tt&gt;infix_register_types&lt;/tt&gt;)',['../md_docs_2signatures.html#autotoc_md166',1,'']]],
  ['types_2ec_89',['types.c',['../types_8c.html',1,'']]]
];
