var searchData=
[
  ['language_0',['Part 1: The Signature Language',['../index.html#autotoc_md9',1,'']]],
  ['language_20binding_1',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md118',1,'']]],
  ['language_20bindings_2',['Chapter 11: Building Language Bindings',['../md_docs_2cookbook.html#autotoc_md117',1,'']]],
  ['language_20reference_3',['Part 2: The Signature Language Reference',['../md_docs_2signatures.html#autotoc_md158',1,'']]],
  ['languages_4',['languages',['../md_docs_2cookbook.html#autotoc_md68',1,'Chapter 5: Interoperability with Other Languages'],['../md_docs_2cookbook.html#autotoc_md72',1,'The Pattern for Other Compiled Languages']]],
  ['large_20structs_20passed_20by_20reference_5',['Recipe: Large Structs Passed by Reference',['../md_docs_2cookbook.html#autotoc_md47',1,'']]],
  ['learn_20more_6',['Learn More',['../index.html#autotoc_md30',1,'']]],
  ['legal_7',['License &amp; Legal',['../index.html#autotoc_md31',1,'']]],
  ['level_20signature_20api_8',['High-Level Signature API',['../group__high__level__api.html',1,'']]],
  ['level_20signature_20api_20tt_20high_5flevel_5fapi_20tt_9',['High-Level Signature API (&lt;tt&gt;high_level_api&lt;/tt&gt;)',['../index.html#autotoc_md20',1,'']]],
  ['libffi_20tt_20and_20tt_20dyncall_20tt_10',['Chapter 10: A Comparative Look: &lt;tt&gt;infix&lt;/tt&gt; vs. &lt;tt&gt;libffi&lt;/tt&gt; and &lt;tt&gt;dyncall&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md102',1,'']]],
  ['libffi_20tt_20approach_11',['libffi tt approach',['../md_docs_2cookbook.html#autotoc_md113',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md109',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md105',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach']]],
  ['libraries_20system_20calls_12',['Chapter 6: Dynamic Libraries &amp; System Calls',['../md_docs_2cookbook.html#autotoc_md80',1,'']]],
  ['libraries_20without_20linking_13',['Recipe: Calling Native System Libraries without Linking',['../md_docs_2cookbook.html#autotoc_md81',1,'']]],
  ['library_14',['library',['../index.html#autotoc_md5',1,'Building the Library'],['../index.html#autotoc_md14',1,'Reading Global Variables from a Shared Library']]],
  ['library_20dependencies_15',['Recipe: Handling Library Dependencies',['../md_docs_2cookbook.html#autotoc_md85',1,'']]],
  ['library_20for_20c_16',['infix: A JIT-Powered FFI Library for C',['../index.html',1,'']]],
  ['library_20globals_20api_17',['Dynamic Library &amp; Globals API',['../group__exports__api.html',1,'']]],
  ['library_20globals_20api_20tt_20exports_5fapi_20tt_18',['Dynamic Library &amp; Globals API (&lt;tt&gt;exports_api&lt;/tt&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['license_19',['license',['../index.html#autotoc_md32',1,'Code License'],['../index.html#autotoc_md33',1,'Documentation License']]],
  ['license_20legal_20',['License &amp; Legal',['../index.html#autotoc_md31',1,'']]],
  ['like_20tt_20printf_20tt_21',['Recipe: Calling Variadic Functions like &lt;tt&gt;printf&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['limitations_20of_20c_20declarations_22',['1.2 The Limitations of C Declarations',['../md_docs_2signatures.html#autotoc_md156',1,'']]],
  ['linking_23',['Recipe: Calling Native System Libraries without Linking',['../md_docs_2cookbook.html#autotoc_md81',1,'']]],
  ['live_20debugging_20with_20gdb_20lldb_24',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md144',1,'']]],
  ['lldb_25',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md144',1,'']]],
  ['loader_2ec_26',['loader.c',['../loader_8c.html',1,'']]],
  ['long_20double_20tt_20strong_27',['&lt;strong&gt;Recipe: Handling &lt;tt&gt;long double&lt;/tt&gt;&lt;/strong&gt;',['../md_docs_2cookbook.html#autotoc_md64',1,'']]],
  ['look_3a_20tt_20infix_20tt_20vs_20tt_20libffi_20tt_20and_20tt_20dyncall_20tt_28',['Chapter 10: A Comparative Look: &lt;tt&gt;infix&lt;/tt&gt; vs. &lt;tt&gt;libffi&lt;/tt&gt; and &lt;tt&gt;dyncall&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md102',1,'']]]
];
