var searchData=
[
  ['table_20emulation_0',['Recipe: Calling a Function Pointer from a Struct (V-Table Emulation)',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['table_20of_20contents_1',['Table of Contents',['../md_docs_2cookbook.html#autotoc_md36',1,'']]],
  ['tables_2',['Formatting Tables',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html#tricks-tables',1,'']]],
  ['tabs_3',['Tabs',['../md_docs_2doxygen-awesome-css_2docs_2extensions.html#extension-tabs',1,'']]],
  ['takeaways_4',['Analysis and Takeaways',['../md_docs_2cookbook.html#autotoc_md111',1,'']]],
  ['target_5ffn_5',['target_fn',['../structinfix__forward__t.html#a3af1080ceceea1dc05bee200422c60d8',1,'infix_forward_t::target_fn'],['../structinfix__call__frame__layout.html#a5eaab27cc161e119694a4508341acf20',1,'infix_call_frame_layout::target_fn']]],
  ['technical_20specification_6',['Part 4: Technical Specification',['../md_docs_2signatures.html#autotoc_md203',1,'']]],
  ['techniques_7',['Chapter 4: Advanced Techniques',['../md_docs_2cookbook.html#autotoc_md59',1,'']]],
  ['templates_8',['Recipe: Interfacing with C++ Templates',['../md_docs_2cookbook.html#autotoc_md68',1,'']]],
  ['test_9',['TEST',['../double__tap_8h.html#ab946e2e7f7679350627acfded8e2658b',1,'double_tap.h']]],
  ['testing_10',['testing',['../md_docs_2internals.html#autotoc_md171',1,'3.4 Fuzz Testing'],['../md_docs_2porting.html#autotoc_md186',1,'Step 5: Testing']]],
  ['that_20contain_20bitfields_11',['Recipe: Working with Structs that Contain Bitfields',['../md_docs_2cookbook.html#autotoc_md49',1,'']]],
  ['the_20abi_20specification_12',['Step 2: Implement the ABI Specification',['../md_docs_2porting.html#autotoc_md183',1,'']]],
  ['the_20basics_20forward_20calls_13',['Chapter 1: The Basics (Forward Calls)',['../md_docs_2cookbook.html#autotoc_md38',1,'']]],
  ['the_20challenge_20of_20interoperability_14',['1.1 The Challenge of Interoperability',['../md_docs_2signatures.html#autotoc_md189',1,'']]],
  ['the_20challenge_3a_20hardened_20runtimes_20on_20apple_20silicon_15',['The Challenge: Hardened Runtimes on Apple Silicon',['../md_docs_2internals.html#autotoc_md169',1,'']]],
  ['the_20entitlement_20fallback_16',['3.3 macOS JIT Hardening and the Entitlement Fallback',['../md_docs_2internals.html#autotoc_md168',1,'']]],
  ['the_20four_20pillars_20of_20a_20language_20binding_17',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md114',1,'']]],
  ['the_20infix_20signature_20and_20type_20system_18',['The infix Signature and Type System',['../md_docs_2signatures.html',1,'']]],
  ['the_20instruction_20emitters_19',['Step 3: Implement the Instruction Emitters',['../md_docs_2porting.html#autotoc_md184',1,'']]],
  ['the_20library_20',['Building the Library',['../index.html#autotoc_md5',1,'']]],
  ['the_20limitations_20of_20c_20declarations_21',['1.2 The Limitations of C Declarations',['../md_docs_2signatures.html#autotoc_md190',1,'']]],
  ['the_20manual_20c_20api_20advanced_22',['Part 3: The Manual C API (Advanced)',['../index.html#autotoc_md15',1,'']]],
  ['the_20named_20type_20registry_23',['the named type registry',['../md_docs_2signatures.html#autotoc_md199',1,'Part 3: The Named Type Registry'],['../index.html#autotoc_md13',1,'Using the Named Type Registry']]],
  ['the_20new_20abi_24',['Step 4: Integrate the New ABI',['../md_docs_2porting.html#autotoc_md185',1,'']]],
  ['the_20pattern_20for_20other_20compiled_20languages_25',['The Pattern for Other Compiled Languages',['../md_docs_2cookbook.html#autotoc_md69',1,'']]],
  ['the_20power_20of_20callbacks_20reverse_20calls_26',['Chapter 3: The Power of Callbacks (Reverse Calls)',['../md_docs_2cookbook.html#autotoc_md55',1,'']]],
  ['the_20self_20contained_20object_20model_27',['The Self-Contained Object Model',['../md_docs_2internals.html#autotoc_md158',1,'']]],
  ['the_20signature_20language_28',['Part 1: The Signature Language',['../index.html#autotoc_md9',1,'']]],
  ['the_20signature_20language_20reference_29',['Part 2: The Signature Language Reference',['../md_docs_2signatures.html#autotoc_md192',1,'']]],
  ['the_20signature_20parser_30',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md85',1,'']]],
  ['the_20trampoline_20generation_20pipeline_31',['The Trampoline Generation Pipeline',['../md_docs_2internals.html#autotoc_md163',1,'']]],
  ['the_20tt_20dyncall_20tt_20approach_32',['the tt dyncall tt approach',['../md_docs_2cookbook.html#autotoc_md100',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md104',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md108',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach']]],
  ['the_20tt_20infix_20tt_20approach_33',['the tt infix tt approach',['../md_docs_2cookbook.html#autotoc_md110',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md106',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md102',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach']]],
  ['the_20tt_20infix_20tt_20ffi_20cookbook_34',['The &lt;tt&gt;infix&lt;/tt&gt; FFI Cookbook',['../md_docs_2cookbook.html',1,'']]],
  ['the_20tt_20infix_20tt_20solution_3a_20runtime_20detection_20with_20graceful_20fallback_35',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md170',1,'']]],
  ['the_20tt_20libffi_20tt_20approach_36',['the tt libffi tt approach',['../md_docs_2cookbook.html#autotoc_md105',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md109',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md101',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach']]],
  ['the_20unity_20build_37',['The Unity Build',['../md_docs_2internals.html#autotoc_md157',1,'']]],
  ['the_20universal_20principle_3a_20the_20c_20abi_38',['The Universal Principle: The C ABI',['../md_docs_2cookbook.html#autotoc_md66',1,'']]],
  ['this_20for_39',['Who is this for?',['../index.html#autotoc_md1',1,'']]],
  ['this_20syntax_40',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md206',1,'']]],
  ['tier_201_3a_20abstract_20c_20types_41',['Tier 1: Abstract C Types',['../md_docs_2signatures.html#autotoc_md194',1,'']]],
  ['tier_202_3a_20explicit_20fixed_20width_20types_20recommended_42',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md195',1,'']]],
  ['tips_20tricks_43',['Tips &amp; Tricks',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html',1,'']]],
  ['to_20a_20new_20platform_44',['Porting &lt;tt&gt;infix&lt;/tt&gt; to a New Platform',['../md_docs_2porting.html',1,'']]],
  ['to_20tt_20infix_20tt_45',['Recipe: Porting a Python Binding from &lt;tt&gt;dyncall&lt;/tt&gt; to &lt;tt&gt;infix&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md115',1,'']]],
  ['toc_46',['Interactive TOC',['../md_docs_2doxygen-awesome-css_2docs_2extensions.html#extension-toc',1,'']]],
  ['todo_47',['TODO',['../double__tap_8h.html#a9c9971e17638fc67630c02c7759c6d2f',1,'double_tap.h']]],
  ['toggle_48',['Dark Mode Toggle',['../md_docs_2doxygen-awesome-css_2docs_2extensions.html#extension-dark-mode-toggle',1,'']]],
  ['tools_49',['Useful Tools',['../md_docs_2internals.html#autotoc_md178',1,'']]],
  ['total_5fstack_5falloc_50',['total_stack_alloc',['../structinfix__reverse__call__frame__layout.html#aedb51aeb6365d359bcb27d1e9920a0d8',1,'infix_reverse_call_frame_layout::total_stack_alloc'],['../structinfix__call__frame__layout.html#a743d543342256cf155458951d48c613e',1,'infix_call_frame_layout::total_stack_alloc']]],
  ['trampoline_20for_20a_20wrapper_51',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_docs_2cookbook.html#autotoc_md87',1,'']]],
  ['trampoline_20generation_20pipeline_52',['The Trampoline Generation Pipeline',['../md_docs_2internals.html#autotoc_md163',1,'']]],
  ['trampoline_2ec_53',['trampoline.c',['../trampoline_8c.html',1,'']]],
  ['trampolines_54',['Best Practice: Caching Trampolines',['../md_docs_2cookbook.html#autotoc_md90',1,'']]],
  ['tricks_55',['Tips &amp; Tricks',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html',1,'']]],
  ['tricks_2emd_56',['tricks.md',['../tricks_8md.html',1,'']]],
  ['troubleshooting_57',['Chapter 9: Common Pitfalls &amp; Troubleshooting',['../md_docs_2cookbook.html#autotoc_md93',1,'']]],
  ['tt_20args_20tt_58',['Mistake: Passing a Value Instead of a Pointer in &lt;tt&gt;args[]&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md94',1,'']]],
  ['tt_20dyncall_20tt_20approach_59',['tt dyncall tt approach',['../md_docs_2cookbook.html#autotoc_md100',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md104',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md108',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach']]],
  ['tt_20dyncall_20tt_20to_20tt_20infix_20tt_60',['Recipe: Porting a Python Binding from &lt;tt&gt;dyncall&lt;/tt&gt; to &lt;tt&gt;infix&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md115',1,'']]],
  ['tt_20error_5fapi_20tt_61',['Error Handling API (&lt;tt&gt;error_api&lt;/tt&gt;)',['../index.html#autotoc_md26',1,'']]],
  ['tt_20exports_5fapi_20tt_62',['Dynamic Library &amp; Globals API (&lt;tt&gt;exports_api&lt;/tt&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['tt_20high_5flevel_5fapi_20tt_63',['High-Level Signature API (&lt;tt&gt;high_level_api&lt;/tt&gt;)',['../index.html#autotoc_md20',1,'']]],
  ['tt_20infix_20tt_20approach_64',['tt infix tt approach',['../md_docs_2cookbook.html#autotoc_md110',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md106',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md102',1,'The &lt;tt&gt;infix&lt;/tt&gt; Approach']]],
  ['tt_20infix_20tt_20ffi_20cookbook_65',['The &lt;tt&gt;infix&lt;/tt&gt; FFI Cookbook',['../md_docs_2cookbook.html',1,'']]],
  ['tt_20infix_20tt_20signature_20mismatch_66',['Mistake: &lt;tt&gt;infix&lt;/tt&gt; Signature Mismatch',['../md_docs_2cookbook.html#autotoc_md95',1,'']]],
  ['tt_20infix_20tt_20solution_3a_20runtime_20detection_20with_20graceful_20fallback_67',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md170',1,'']]],
  ['tt_20infix_20tt_20to_20a_20new_20platform_68',['Porting &lt;tt&gt;infix&lt;/tt&gt; to a New Platform',['../md_docs_2porting.html',1,'']]],
  ['tt_20infix_20tt_20vs_20tt_20libffi_20tt_20and_20tt_20dyncall_20tt_69',['Chapter 10: A Comparative Look: &lt;tt&gt;infix&lt;/tt&gt; vs. &lt;tt&gt;libffi&lt;/tt&gt; and &lt;tt&gt;dyncall&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md98',1,'']]],
  ['tt_20infix_5fdump_5fhex_20tt_70',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_docs_2internals.html#autotoc_md176',1,'']]],
  ['tt_20infix_5fregister_5ftypes_20tt_71',['Defining Types (&lt;tt&gt;infix_register_types&lt;/tt&gt;)',['../md_docs_2signatures.html#autotoc_md200',1,'']]],
  ['tt_20introspection_5fapi_20tt_72',['Introspection API (&lt;tt&gt;introspection_api&lt;/tt&gt;)',['../index.html#autotoc_md25',1,'']]],
  ['tt_20libffi_20tt_20approach_73',['tt libffi tt approach',['../md_docs_2cookbook.html#autotoc_md101',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md105',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md109',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach']]],
  ['tt_20manual_5fapi_20tt_74',['Manual API (&lt;tt&gt;manual_api&lt;/tt&gt;)',['../index.html#autotoc_md22',1,'']]],
  ['tt_20memory_5fmanagement_20tt_75',['Memory Management (&lt;tt&gt;memory_management&lt;/tt&gt;)',['../index.html#autotoc_md24',1,'']]],
  ['tt_20printf_20tt_76',['Recipe: Calling Variadic Functions like &lt;tt&gt;printf&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md60',1,'']]],
  ['tt_20qsort_20tt_77',['Recipe: Creating a Stateless Callback for &lt;tt&gt;qsort&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md56',1,'']]],
  ['tt_20registry_5fapi_20tt_78',['Named Type Registry (&lt;tt&gt;registry_api&lt;/tt&gt;)',['../index.html#autotoc_md19',1,'']]],
  ['tt_20src_20common_20infix_5fconfig_20h_20tt_79',['Step 1: Platform Detection (&lt;tt&gt;src/common/infix_config.h&lt;/tt&gt;)',['../md_docs_2porting.html#autotoc_md182',1,'']]],
  ['tt_20type_5fsystem_20tt_80',['Type System (&lt;tt&gt;type_system&lt;/tt&gt;)',['../index.html#autotoc_md23',1,'']]],
  ['type_81',['type',['../structinfix__struct__member__t.html#aa89e6621da98f5115dcc807599c4ac77',1,'infix_struct_member_t::type'],['../structinfix__function__argument__t.html#a1bd256c75cb6ec767cec121370e6a0ed',1,'infix_function_argument_t::type'],['../struct__infix__registry__entry__t.html#a5337bf58d6fcd7fa8b08a9ac483c6702',1,'_infix_registry_entry_t::type'],['../structinfix__arg__location.html#a4f53bb713bc5749863d8ba2633b74604',1,'infix_arg_location::type']]],
  ['type_20constructors_20and_20composite_20structures_82',['2.2 Type Constructors and Composite Structures',['../md_docs_2signatures.html#autotoc_md196',1,'']]],
  ['type_20creation_20api_83',['Manual Type-Creation API',['../group__manual__api.html',1,'']]],
  ['type_20registry_84',['type registry',['../md_docs_2signatures.html#autotoc_md199',1,'Part 3: The Named Type Registry'],['../index.html#autotoc_md13',1,'Using the Named Type Registry']]],
  ['type_20registry_20api_85',['Named Type Registry API',['../group__registry__api.html',1,'']]],
  ['type_20registry_20tt_20registry_5fapi_20tt_86',['Named Type Registry (&lt;tt&gt;registry_api&lt;/tt&gt;)',['../index.html#autotoc_md19',1,'']]],
  ['type_20system_87',['type system',['../md_docs_2signatures.html',1,'The infix Signature and Type System'],['../group__type__system.html',1,'Type System']]],
  ['type_20system_20tt_20type_5fsystem_20tt_88',['Type System (&lt;tt&gt;type_system&lt;/tt&gt;)',['../index.html#autotoc_md23',1,'']]],
  ['type_5fregistry_2ec_89',['type_registry.c',['../type__registry_8c.html',1,'']]],
  ['type_5fsystem_20tt_90',['Type System (&lt;tt&gt;type_system&lt;/tt&gt;)',['../index.html#autotoc_md23',1,'']]],
  ['types_91',['types',['../md_docs_2cookbook.html#autotoc_md91',1,'Recipe: Using a Custom Arena for a Group of Types'],['../md_docs_2cookbook.html#autotoc_md42',1,'Recipe: Working with Opaque Pointers (Incomplete Types)'],['../md_docs_2signatures.html#autotoc_md194',1,'Tier 1: Abstract C Types'],['../md_docs_2signatures.html#autotoc_md201',1,'Using Named Types']]],
  ['types_20recommended_92',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md195',1,'']]],
  ['types_20tt_20infix_5fregister_5ftypes_20tt_93',['Defining Types (&lt;tt&gt;infix_register_types&lt;/tt&gt;)',['../md_docs_2signatures.html#autotoc_md200',1,'']]],
  ['types_2ec_94',['types.c',['../types_8c.html',1,'']]]
];
