var searchData=
[
  ['dark_20mode_0',['Disable Dark Mode',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html#tricks-darkmode',1,'']]],
  ['dark_20mode_20toggle_1',['Dark Mode Toggle',['../md_docs_2doxygen-awesome-css_2docs_2extensions.html#extension-dark-mode-toggle',1,'']]],
  ['data_20marshalling_2',['data marshalling',['../md_docs_2cookbook.html#autotoc_md87',1,'Chapter 7: Introspection for Data Marshalling'],['../index.html#autotoc_md16',1,'Powerful Introspection for Dynamic Data Marshalling']]],
  ['data_20structures_3',['Chapter 2: Handling Complex Data Structures',['../md_docs_2cookbook.html#autotoc_md44',1,'']]],
  ['debugging_20guide_4',['5. Maintainer&apos;s Debugging Guide',['../md_docs_2internals.html#autotoc_md179',1,'']]],
  ['debugging_20with_20gdb_20lldb_5',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md181',1,'']]],
  ['decisions_6',['1.2 Key Architectural Decisions',['../md_docs_2internals.html#autotoc_md160',1,'']]],
  ['declarations_7',['1.2 The Limitations of C Declarations',['../md_docs_2signatures.html#autotoc_md194',1,'']]],
  ['deep_20dive_8',['3. Security Features Deep Dive',['../md_docs_2internals.html#autotoc_md169',1,'']]],
  ['defining_20types_20tt_20infix_5fregister_5ftypes_20tt_9',['Defining Types (&lt;tt&gt;infix_register_types&lt;/tt&gt;)',['../md_docs_2signatures.html#autotoc_md204',1,'']]],
  ['dependencies_10',['Recipe: Handling Library Dependencies',['../md_docs_2cookbook.html#autotoc_md85',1,'']]],
  ['dependency_11',['npm/xpm dependency',['..//home/runner/work/infix/infix/docs/doxygen-awesome-css/README.md#autotoc_md151',1,'']]],
  ['depth_12',['depth',['../structparser__state.html#aa6acb3fad5e4ab8d8a0a656402ff13a4',1,'parser_state']]],
  ['design_20philosophy_13',['1. Core Design Philosophy',['../md_docs_2internals.html#autotoc_md158',1,'']]],
  ['design_20rationale_3a_20why_20this_20syntax_14',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md210',1,'']]],
  ['detection_20tt_20src_20common_20infix_5fconfig_20h_20tt_15',['Step 1: Platform Detection (&lt;tt&gt;src/common/infix_config.h&lt;/tt&gt;)',['../md_docs_2porting.html#autotoc_md186',1,'']]],
  ['detection_20with_20graceful_20fallback_16',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md174',1,'']]],
  ['diag_17',['diag',['../double__tap_8h.html#a1d83e69b4252e4052fc5215c44f90c0d',1,'double_tap.h']]],
  ['diagrams_20with_20graphviz_18',['Diagrams with Graphviz',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html#tricks-graphviz',1,'']]],
  ['directly_19',['Recipe: Interfacing with a C++ Class (Directly)',['../md_docs_2cookbook.html#autotoc_md70',1,'']]],
  ['disable_20dark_20mode_20',['Disable Dark Mode',['../md_docs_2doxygen-awesome-css_2docs_2tricks.html#tricks-darkmode',1,'']]],
  ['dive_21',['3. Security Features Deep Dive',['../md_docs_2internals.html#autotoc_md169',1,'']]],
  ['dlang_22',['Dlang',['../md_docs_2cookbook.html#autotoc_md77',1,'']]],
  ['documentation_23',['External ABI Documentation',['../md_docs_2internals.html#autotoc_md183',1,'']]],
  ['documentation_20license_24',['Documentation License',['../index.html#autotoc_md33',1,'']]],
  ['done_25',['done',['../double__tap_8h.html#a4c29258cb6b467ba162cfe09d50a6ad7',1,'double_tap.h']]],
  ['double_20tt_20strong_26',['&lt;strong&gt;Recipe: Handling &lt;tt&gt;long double&lt;/tt&gt;&lt;/strong&gt;',['../md_docs_2cookbook.html#autotoc_md64',1,'']]],
  ['double_5ftap_2eh_27',['double_tap.h',['../double__tap_8h.html',1,'']]],
  ['doxygen_20generator_28',['Doxygen generator',['../md_docs_2doxygen-awesome-css_2docs_2customization.html#autotoc_md124',1,'']]],
  ['dynamic_20data_20marshalling_29',['Powerful Introspection for Dynamic Data Marshalling',['../index.html#autotoc_md16',1,'']]],
  ['dynamic_20libraries_20system_20calls_30',['Chapter 6: Dynamic Libraries &amp; System Calls',['../md_docs_2cookbook.html#autotoc_md80',1,'']]],
  ['dynamic_20library_20globals_20api_31',['Dynamic Library &amp; Globals API',['../group__exports__api.html',1,'']]],
  ['dynamic_20library_20globals_20api_20tt_20exports_5fapi_20tt_32',['Dynamic Library &amp; Globals API (&lt;tt&gt;exports_api&lt;/tt&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['dynamic_20struct_20marshalling_20with_20the_20signature_20parser_33',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md88',1,'']]],
  ['dyncall_20tt_34',['Chapter 10: A Comparative Look: &lt;tt&gt;infix&lt;/tt&gt; vs. &lt;tt&gt;libffi&lt;/tt&gt; and &lt;tt&gt;dyncall&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md102',1,'']]],
  ['dyncall_20tt_20approach_35',['dyncall tt approach',['../md_docs_2cookbook.html#autotoc_md112',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md108',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md104',1,'The &lt;tt&gt;dyncall&lt;/tt&gt; Approach']]],
  ['dyncall_20tt_20to_20tt_20infix_20tt_36',['Recipe: Porting a Python Binding from &lt;tt&gt;dyncall&lt;/tt&gt; to &lt;tt&gt;infix&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md119',1,'']]]
];
