var searchData=
[
  ['w_20x_0',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md175',1,'']]],
  ['w_20x_20write_20xor_20execute_20memory_20policy_1',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md237',1,'']]],
  ['wchar_5ft_20tt_20etc_2',['Recipe: Handling Strings and Semantic Types (&lt;tt&gt;wchar_t&lt;/tt&gt;, etc.)',['../md_docs_2cookbook.html#autotoc_md83',1,'']]],
  ['whitespace_20and_20comments_3',['4.1 Whitespace and Comments',['../md_docs_2signatures.html#autotoc_md213',1,'']]],
  ['who_20is_20this_20for_4',['Who is this for?',['../index.html#autotoc_md5',1,'']]],
  ['why_20it_20s_20better_5',['How It Works &amp; Why It&apos;s Better',['../md_docs_2cookbook.html#autotoc_md107',1,'']]],
  ['why_20this_20syntax_6',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md215',1,'']]],
  ['width_20types_20recommended_7',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md203',1,'']]],
  ['win32_5fmsgbox_2ec_8',['win32_msgbox.c',['../win32__msgbox_8c.html',1,'']]],
  ['windows_20with_20msvc_9',['NMake (Windows with MSVC)',['../md_docs_2INSTALL.html#autotoc_md148',1,'']]],
  ['with_20a_20c_20class_20directly_10',['Recipe: Interfacing with a C++ Class (Directly)',['../md_docs_2cookbook.html#autotoc_md73',1,'']]],
  ['with_20a_20struct_11',['Scenario 2: Calling a Function with a Struct',['../md_docs_2cookbook.html#autotoc_md121',1,'']]],
  ['with_20an_20arena_12',['Recipe: Building a Dynamic Call Frame with an Arena',['../md_docs_2cookbook.html#autotoc_md106',1,'']]],
  ['with_20c_20templates_13',['Recipe: Interfacing with C++ Templates',['../md_docs_2cookbook.html#autotoc_md74',1,'']]],
  ['with_20complex_20numbers_14',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md49',1,'']]],
  ['with_20enums_15',['Recipe: Working with Enums',['../md_docs_2cookbook.html#autotoc_md57',1,'']]],
  ['with_20fixed_20size_20arrays_16',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md47',1,'']]],
  ['with_20gdb_20lldb_17',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md186',1,'']]],
  ['with_20graceful_20fallback_18',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md179',1,'']]],
  ['with_20msvc_19',['NMake (Windows with MSVC)',['../md_docs_2INSTALL.html#autotoc_md148',1,'']]],
  ['with_20nested_20ffi_20calls_20',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_docs_2cookbook.html#autotoc_md68',1,'']]],
  ['with_20opaque_20pointers_20incomplete_20types_21',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md38',1,'']]],
  ['with_20other_20languages_22',['Chapter 5: Interoperability with Other Languages',['../md_docs_2cookbook.html#autotoc_md71',1,'']]],
  ['with_20other_20systems_23',['4.4 Comparison with Other Systems',['../md_docs_2signatures.html#autotoc_md216',1,'']]],
  ['with_20out_20parameters_24',['Recipe: Working with &quot;Out&quot; Parameters',['../md_docs_2cookbook.html#autotoc_md37',1,'']]],
  ['with_20packed_20structs_25',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md44',1,'']]],
  ['with_20semantic_20awareness_26',['Step 3: Introspect with Semantic Awareness',['../md_docs_2cookbook.html#autotoc_md86',1,'']]],
  ['with_20simd_20vectors_27',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md50',1,'']]],
  ['with_20structs_20that_20contain_20bitfields_28',['Recipe: Working with Structs that Contain Bitfields',['../md_docs_2cookbook.html#autotoc_md45',1,'']]],
  ['with_20the_20signature_20parser_29',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md97',1,'']]],
  ['with_20tt_20find_5fpackage_20tt_30',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md_docs_2INSTALL.html#autotoc_md152',1,'']]],
  ['with_20tt_20infix_5fdump_5fhex_20tt_31',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_docs_2internals.html#autotoc_md185',1,'']]],
  ['with_20unions_32',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md46',1,'']]],
  ['without_20linking_33',['Recipe: Calling Native System Libraries without Linking',['../md_docs_2cookbook.html#autotoc_md90',1,'']]],
  ['worker_5fthread_5ffunc_34',['worker_thread_func',['../Ch04__Rec06__ThreadSafety_8c.html#aa3b119e6278d644b02d45b6bfdf1d3ac',1,'Ch04_Rec06_ThreadSafety.c']]],
  ['working_20with_20complex_20numbers_35',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md49',1,'']]],
  ['working_20with_20enums_36',['Recipe: Working with Enums',['../md_docs_2cookbook.html#autotoc_md57',1,'']]],
  ['working_20with_20fixed_20size_20arrays_37',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md47',1,'']]],
  ['working_20with_20opaque_20pointers_20incomplete_20types_38',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md38',1,'']]],
  ['working_20with_20out_20parameters_39',['Recipe: Working with &quot;Out&quot; Parameters',['../md_docs_2cookbook.html#autotoc_md37',1,'']]],
  ['working_20with_20packed_20structs_40',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md44',1,'']]],
  ['working_20with_20simd_20vectors_41',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md50',1,'']]],
  ['working_20with_20structs_20that_20contain_20bitfields_42',['Recipe: Working with Structs that Contain Bitfields',['../md_docs_2cookbook.html#autotoc_md45',1,'']]],
  ['working_20with_20unions_43',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md46',1,'']]],
  ['works_20why_20it_20s_20better_44',['How It Works &amp; Why It&apos;s Better',['../md_docs_2cookbook.html#autotoc_md107',1,'']]],
  ['works_3a_20the_20trampoline_20concept_45',['How It Works: The Trampoline Concept',['../index.html#autotoc_md2',1,'']]],
  ['wrapper_46',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_docs_2cookbook.html#autotoc_md99',1,'']]],
  ['write_20xor_20execute_20memory_20policy_47',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md237',1,'']]],
  ['write_20xor_20execute_20w_20x_48',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md175',1,'']]],
  ['writing_20global_20variables_49',['Recipe: Reading and Writing Global Variables',['../md_docs_2cookbook.html#autotoc_md91',1,'']]]
];
