var searchData=
[
  ['w_20x_0',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md196',1,'']]],
  ['w_20x_20write_20xor_20execute_20memory_20policy_1',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md289',1,'']]],
  ['way_3a_20add_20tt_20infix_20tt_20directly_20to_20your_20project_2',['1. The Easiest Way: Add &lt;tt&gt;infix&lt;/tt&gt; Directly to Your Project',['../md_docs_2INSTALL.html#autotoc_md166',1,'']]],
  ['wchar_5ft_20tt_20etc_3',['Recipe: Handling Strings and Semantic Types (&lt;tt&gt;wchar_t&lt;/tt&gt;, etc.)',['../md_docs_2cookbook.html#autotoc_md108',1,'']]],
  ['whitespace_20and_20comments_4',['4.1 Whitespace and Comments',['../md_docs_2signatures.html#autotoc_md244',1,'']]],
  ['why_20it_20s_20better_5',['How It Works &amp; Why It&apos;s Better',['../md_docs_2cookbook.html#autotoc_md131',1,'']]],
  ['why_20this_20matters_20for_20strings_6',['Why this matters for Strings',['../md_docs_2signatures.html#autotoc_md237',1,'']]],
  ['why_20this_20syntax_7',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md246',1,'']]],
  ['width_20types_20recommended_8',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md230',1,'']]],
  ['win32_5fmsgbox_2ec_9',['win32_msgbox.c',['../win32__msgbox_8c.html',1,'']]],
  ['with_20a_20c_20class_20directly_10',['Recipe: Interfacing with a C++ Class (Directly)',['../md_docs_2cookbook.html#autotoc_md98',1,'']]],
  ['with_20a_20shared_20arena_11',['Recipe: Optimizing Memory with a Shared Arena',['../md_docs_2cookbook.html#autotoc_md129',1,'']]],
  ['with_20a_20struct_12',['Scenario 2: Calling a Function with a Struct',['../md_docs_2cookbook.html#autotoc_md145',1,'']]],
  ['with_20an_20arena_13',['Recipe: Building a Dynamic Call Frame with an Arena',['../md_docs_2cookbook.html#autotoc_md130',1,'']]],
  ['with_20bitfields_14',['Recipe: Working with Bitfields',['../md_docs_2cookbook.html#autotoc_md69',1,'']]],
  ['with_20c_20templates_15',['Recipe: Interfacing with C++ Templates',['../md_docs_2cookbook.html#autotoc_md99',1,'']]],
  ['with_20complex_20numbers_16',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md74',1,'']]],
  ['with_20enums_17',['Recipe: Working with Enums',['../md_docs_2cookbook.html#autotoc_md82',1,'']]],
  ['with_20fixed_20size_20arrays_18',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md72',1,'']]],
  ['with_20flexible_20array_20members_20fam_19',['Recipe: Working with Flexible Array Members (FAM)',['../md_docs_2cookbook.html#autotoc_md70',1,'']]],
  ['with_20gdb_20lldb_20',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md212',1,'']]],
  ['with_20graceful_20fallback_21',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md200',1,'']]],
  ['with_20nested_20ffi_20calls_22',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_docs_2cookbook.html#autotoc_md93',1,'']]],
  ['with_20opaque_20pointers_20incomplete_20types_23',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['with_20other_20languages_24',['Chapter 5: Interoperability with Other Languages',['../md_docs_2cookbook.html#autotoc_md96',1,'']]],
  ['with_20other_20systems_25',['4.4 Comparison with Other Systems',['../md_docs_2signatures.html#autotoc_md247',1,'']]],
  ['with_20out_20parameters_26',['Recipe: Working with &quot;Out&quot; Parameters',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['with_20packed_20structs_27',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md68',1,'']]],
  ['with_20simd_20vectors_28',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md75',1,'']]],
  ['with_20the_20signature_20parser_29',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md120',1,'']]],
  ['with_20tt_20find_5fpackage_20tt_30',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md_docs_2INSTALL.html#autotoc_md177',1,'']]],
  ['with_20tt_20infix_5fdump_5fhex_20tt_31',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_docs_2internals.html#autotoc_md211',1,'']]],
  ['with_20unions_32',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md71',1,'']]],
  ['without_20linking_33',['Recipe: Calling Native System Libraries without Linking',['../md_docs_2cookbook.html#autotoc_md112',1,'']]],
  ['worker_5fthread_5ffunc_34',['worker_thread_func',['../Ch04__ThreadSafety_8c.html#aa3b119e6278d644b02d45b6bfdf1d3ac',1,'Ch04_ThreadSafety.c']]],
  ['working_20with_20bitfields_35',['Recipe: Working with Bitfields',['../md_docs_2cookbook.html#autotoc_md69',1,'']]],
  ['working_20with_20complex_20numbers_36',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md74',1,'']]],
  ['working_20with_20enums_37',['Recipe: Working with Enums',['../md_docs_2cookbook.html#autotoc_md82',1,'']]],
  ['working_20with_20fixed_20size_20arrays_38',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md72',1,'']]],
  ['working_20with_20flexible_20array_20members_20fam_39',['Recipe: Working with Flexible Array Members (FAM)',['../md_docs_2cookbook.html#autotoc_md70',1,'']]],
  ['working_20with_20opaque_20pointers_20incomplete_20types_40',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['working_20with_20out_20parameters_41',['Recipe: Working with &quot;Out&quot; Parameters',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['working_20with_20packed_20structs_42',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md68',1,'']]],
  ['working_20with_20simd_20vectors_43',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md75',1,'']]],
  ['working_20with_20unions_44',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md71',1,'']]],
  ['works_20why_20it_20s_20better_45',['How It Works &amp; Why It&apos;s Better',['../md_docs_2cookbook.html#autotoc_md131',1,'']]],
  ['works_3a_20a_20quick_20example_46',['How It Works: A Quick Example',['../index.html#autotoc_md4',1,'']]],
  ['wrapper_47',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_docs_2cookbook.html#autotoc_md122',1,'']]],
  ['write_20xor_20execute_20memory_20policy_48',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md289',1,'']]],
  ['write_20xor_20execute_20w_20x_49',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md196',1,'']]],
  ['writeback_5fhandler_50',['writeback_handler',['../group__high__level__api.html#ga60d81312a9c9798a4a1dc03faf616ac5',1,'infix_direct_arg_handler_t']]],
  ['writeback_5fmock_5fpoint_51',['writeback_mock_point',['../Ch12__DirectMarshalling_8c.html#a8905932ed4cac9c25b46336baec581b2',1,'Ch12_DirectMarshalling.c']]],
  ['writing_20global_20variables_52',['Recipe: Reading and Writing Global Variables',['../md_docs_2cookbook.html#autotoc_md113',1,'']]]
];
