var searchData=
[
  ['language_0',['Part 1: The Signature Language',['../index.html#autotoc_md9',1,'']]],
  ['language_20binding_1',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md121',1,'']]],
  ['language_20bindings_2',['Chapter 11: Building Language Bindings',['../md_docs_2cookbook.html#autotoc_md120',1,'']]],
  ['language_20reference_3',['Part 2: The Signature Language Reference',['../md_docs_2signatures.html#autotoc_md188',1,'']]],
  ['languages_4',['languages',['../md_docs_2cookbook.html#autotoc_md68',1,'Chapter 5: Interoperability with Other Languages'],['../md_docs_2cookbook.html#autotoc_md72',1,'The Pattern for Other Compiled Languages']]],
  ['large_20structs_20passed_20by_20reference_5',['Recipe: Large Structs Passed by Reference',['../md_docs_2cookbook.html#autotoc_md47',1,'']]],
  ['large_5fstack_5fcallee_6',['large_stack_callee',['../401__large__stack_8c.html#a8d9b25f0d708a936741592612cc6abfa',1,'401_large_stack.c']]],
  ['large_5fstruct_5fpass_5fhandler_7',['large_struct_pass_handler',['../203__complex_8c.html#ac84a68db4e3aae7e761f6ed7196ce3e2',1,'large_struct_pass_handler(infix_context_t *context, LargeStruct s):&#160;203_complex.c'],['../302__aggregates_8c.html#ac84a68db4e3aae7e761f6ed7196ce3e2',1,'large_struct_pass_handler(infix_context_t *context, LargeStruct s):&#160;302_aggregates.c']]],
  ['large_5fstruct_5freturn_5fhandler_8',['large_struct_return_handler',['../302__aggregates_8c.html#a534b99cfc4e2eb58aa6b1912be1f7c62',1,'large_struct_return_handler(infix_context_t *context, int a):&#160;302_aggregates.c'],['../203__complex_8c.html#a534b99cfc4e2eb58aa6b1912be1f7c62',1,'large_struct_return_handler(infix_context_t *context, int a):&#160;203_complex.c']]],
  ['largedata_9',['LargeData',['../structLargeData.html',1,'']]],
  ['largestruct_10',['LargeStruct',['../structLargeStruct.html',1,'']]],
  ['learn_20more_11',['Learn More',['../index.html#autotoc_md30',1,'']]],
  ['legal_12',['License &amp; Legal',['../index.html#autotoc_md31',1,'']]],
  ['level_20signature_20api_13',['High-Level Signature API',['../group__high__level__api.html',1,'']]],
  ['level_20signature_20api_20tt_20high_5flevel_5fapi_20tt_14',['High-Level Signature API (&lt;tt&gt;high_level_api&lt;/tt&gt;)',['../index.html#autotoc_md20',1,'']]],
  ['libffi_20tt_20and_20tt_20dyncall_20tt_15',['Chapter 10: A Comparative Look: &lt;tt&gt;infix&lt;/tt&gt; vs. &lt;tt&gt;libffi&lt;/tt&gt; and &lt;tt&gt;dyncall&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md105',1,'']]],
  ['libffi_20tt_20approach_16',['libffi tt approach',['../md_docs_2cookbook.html#autotoc_md108',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md112',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach'],['../md_docs_2cookbook.html#autotoc_md116',1,'The &lt;tt&gt;libffi&lt;/tt&gt; Approach']]],
  ['libraries_20system_20calls_17',['Chapter 6: Dynamic Libraries &amp; System Calls',['../md_docs_2cookbook.html#autotoc_md80',1,'']]],
  ['libraries_20without_20linking_18',['Recipe: Calling Native System Libraries without Linking',['../md_docs_2cookbook.html#autotoc_md81',1,'']]],
  ['library_19',['library',['../index.html#autotoc_md5',1,'Building the Library'],['../index.html#autotoc_md14',1,'Reading Global Variables from a Shared Library']]],
  ['library_20dependencies_20',['Recipe: Handling Library Dependencies',['../md_docs_2cookbook.html#autotoc_md85',1,'']]],
  ['library_20for_20c_21',['infix: A JIT-Powered FFI Library for C',['../index.html',1,'']]],
  ['library_20globals_20api_22',['Dynamic Library &amp; Globals API',['../group__exports__api.html',1,'']]],
  ['library_20globals_20api_20tt_20exports_5fapi_20tt_23',['Dynamic Library &amp; Globals API (&lt;tt&gt;exports_api&lt;/tt&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['license_24',['license',['../index.html#autotoc_md32',1,'Code License'],['../index.html#autotoc_md33',1,'Documentation License']]],
  ['license_20legal_25',['License &amp; Legal',['../index.html#autotoc_md31',1,'']]],
  ['like_20tt_20printf_20tt_26',['Recipe: Calling Variadic Functions like &lt;tt&gt;printf&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['limitations_20of_20c_20declarations_27',['1.2 The Limitations of C Declarations',['../md_docs_2signatures.html#autotoc_md186',1,'']]],
  ['linking_28',['Recipe: Calling Native System Libraries without Linking',['../md_docs_2cookbook.html#autotoc_md81',1,'']]],
  ['linux_20distributions_20deb_20rpm_29',['Linux Distributions (DEB/RPM)',['../md_docs_2INSTALL.html#autotoc_md148',1,'']]],
  ['linux_20macos_20bsds_30',['GNU Make (Linux, macOS, BSDs)',['../md_docs_2INSTALL.html#autotoc_md135',1,'']]],
  ['list10_31',['LIST10',['../401__large__stack_8c.html#ad913dae1bd62e1aec29d8b557df6f21d',1,'401_large_stack.c']]],
  ['list100_32',['LIST100',['../401__large__stack_8c.html#abe34be58e85259442d89c13a804cedda',1,'401_large_stack.c']]],
  ['live_20debugging_20with_20gdb_20lldb_33',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md174',1,'']]],
  ['lldb_34',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md174',1,'']]],
  ['loader_2ec_35',['loader.c',['../loader_8c.html',1,'']]],
  ['long_20double_20tt_36',['Recipe: Handling &lt;tt&gt;long double&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md64',1,'']]],
  ['look_3a_20tt_20infix_20tt_20vs_20tt_20libffi_20tt_20and_20tt_20dyncall_20tt_37',['Chapter 10: A Comparative Look: &lt;tt&gt;infix&lt;/tt&gt; vs. &lt;tt&gt;libffi&lt;/tt&gt; and &lt;tt&gt;dyncall&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md105',1,'']]],
  ['loops_38',['Advanced Optimization: Arena Resetting for Hot Loops',['../md_docs_2cookbook.html#autotoc_md98',1,'']]]
];
