var searchData=
[
  ['w_20x_0',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md179',1,'']]],
  ['w_20x_20write_20xor_20execute_20memory_20policy_1',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md245',1,'']]],
  ['way_3a_20add_20tt_20infix_20tt_20directly_20to_20your_20project_2',['1. The Easiest Way: Add &lt;tt&gt;infix&lt;/tt&gt; Directly to Your Project',['../md_docs_2INSTALL.html#autotoc_md151',1,'']]],
  ['wchar_5ft_20tt_20etc_3',['Recipe: Handling Strings and Semantic Types (&lt;tt&gt;wchar_t&lt;/tt&gt;, etc.)',['../md_docs_2cookbook.html#autotoc_md98',1,'']]],
  ['whitespace_20and_20comments_4',['4.1 Whitespace and Comments',['../md_docs_2signatures.html#autotoc_md217',1,'']]],
  ['why_20it_20s_20better_5',['How It Works &amp; Why It&apos;s Better',['../md_docs_2cookbook.html#autotoc_md121',1,'']]],
  ['why_20this_20syntax_6',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md219',1,'']]],
  ['width_20types_20recommended_7',['Tier 2: Explicit Fixed-Width Types (Recommended)',['../md_docs_2signatures.html#autotoc_md207',1,'']]],
  ['win32_5fmsgbox_2ec_8',['win32_msgbox.c',['../win32__msgbox_8c.html',1,'']]],
  ['with_20a_20c_20class_20directly_9',['Recipe: Interfacing with a C++ Class (Directly)',['../md_docs_2cookbook.html#autotoc_md88',1,'']]],
  ['with_20a_20shared_20arena_10',['Recipe: Optimizing Memory with a Shared Arena',['../md_docs_2cookbook.html#autotoc_md119',1,'']]],
  ['with_20a_20struct_11',['Scenario 2: Calling a Function with a Struct',['../md_docs_2cookbook.html#autotoc_md135',1,'']]],
  ['with_20an_20arena_12',['Recipe: Building a Dynamic Call Frame with an Arena',['../md_docs_2cookbook.html#autotoc_md120',1,'']]],
  ['with_20c_20templates_13',['Recipe: Interfacing with C++ Templates',['../md_docs_2cookbook.html#autotoc_md89',1,'']]],
  ['with_20complex_20numbers_14',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md64',1,'']]],
  ['with_20enums_15',['Recipe: Working with Enums',['../md_docs_2cookbook.html#autotoc_md72',1,'']]],
  ['with_20fixed_20size_20arrays_16',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['with_20gdb_20lldb_17',['Method 2: Live Debugging with GDB/LLDB',['../md_docs_2internals.html#autotoc_md190',1,'']]],
  ['with_20graceful_20fallback_18',['The &lt;tt&gt;infix&lt;/tt&gt; Solution: Runtime Detection with Graceful Fallback',['../md_docs_2internals.html#autotoc_md183',1,'']]],
  ['with_20nested_20ffi_20calls_19',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_docs_2cookbook.html#autotoc_md83',1,'']]],
  ['with_20opaque_20pointers_20incomplete_20types_20',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md53',1,'']]],
  ['with_20other_20languages_21',['Chapter 5: Interoperability with Other Languages',['../md_docs_2cookbook.html#autotoc_md86',1,'']]],
  ['with_20other_20systems_22',['4.4 Comparison with Other Systems',['../md_docs_2signatures.html#autotoc_md220',1,'']]],
  ['with_20out_20parameters_23',['Recipe: Working with &quot;Out&quot; Parameters',['../md_docs_2cookbook.html#autotoc_md52',1,'']]],
  ['with_20packed_20structs_24',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md59',1,'']]],
  ['with_20simd_20vectors_25',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md65',1,'']]],
  ['with_20structs_20that_20contain_20bitfields_26',['Recipe: Working with Structs that Contain Bitfields',['../md_docs_2cookbook.html#autotoc_md60',1,'']]],
  ['with_20the_20signature_20parser_27',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md110',1,'']]],
  ['with_20tt_20find_5fpackage_20tt_28',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md_docs_2INSTALL.html#autotoc_md161',1,'']]],
  ['with_20tt_20infix_5fdump_5fhex_20tt_29',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_docs_2internals.html#autotoc_md189',1,'']]],
  ['with_20unions_30',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['without_20linking_31',['Recipe: Calling Native System Libraries without Linking',['../md_docs_2cookbook.html#autotoc_md102',1,'']]],
  ['worker_5fthread_5ffunc_32',['worker_thread_func',['../Ch04__ThreadSafety_8c.html#aa3b119e6278d644b02d45b6bfdf1d3ac',1,'Ch04_ThreadSafety.c']]],
  ['working_20with_20complex_20numbers_33',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md64',1,'']]],
  ['working_20with_20enums_34',['Recipe: Working with Enums',['../md_docs_2cookbook.html#autotoc_md72',1,'']]],
  ['working_20with_20fixed_20size_20arrays_35',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['working_20with_20opaque_20pointers_20incomplete_20types_36',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md53',1,'']]],
  ['working_20with_20out_20parameters_37',['Recipe: Working with &quot;Out&quot; Parameters',['../md_docs_2cookbook.html#autotoc_md52',1,'']]],
  ['working_20with_20packed_20structs_38',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md59',1,'']]],
  ['working_20with_20simd_20vectors_39',['Recipe: Working with SIMD Vectors',['../md_docs_2cookbook.html#autotoc_md65',1,'']]],
  ['working_20with_20structs_20that_20contain_20bitfields_40',['Recipe: Working with Structs that Contain Bitfields',['../md_docs_2cookbook.html#autotoc_md60',1,'']]],
  ['working_20with_20unions_41',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['works_20why_20it_20s_20better_42',['How It Works &amp; Why It&apos;s Better',['../md_docs_2cookbook.html#autotoc_md121',1,'']]],
  ['works_3a_20a_20quick_20example_43',['How It Works: A Quick Example',['../index.html#autotoc_md4',1,'']]],
  ['wrapper_44',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_docs_2cookbook.html#autotoc_md112',1,'']]],
  ['write_20xor_20execute_20memory_20policy_45',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md245',1,'']]],
  ['write_20xor_20execute_20w_20x_46',['3.1 Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md179',1,'']]],
  ['writing_20global_20variables_47',['Recipe: Reading and Writing Global Variables',['../md_docs_2cookbook.html#autotoc_md103',1,'']]]
];
