var searchData=
[
  ['w_20x_0',['Write XOR Execute (W^X)',['../md_internals.html#autotoc_md137',1,'']]],
  ['w_20x_20write_20xor_20execute_20memory_20policy_1',['1. W^X (Write XOR Execute) Memory Policy',['../md__2home_2runner_2work_2infix_2infix_2SECURITY.html#autotoc_md220',1,'']]],
  ['way_2',['Recipe: Creating a Stateful Callback (The Modern Way)',['../md_cookbook.html#autotoc_md83',1,'']]],
  ['whitespace_20and_20comments_3',['4.1 Whitespace and Comments',['../md_signatures.html#autotoc_md172',1,'']]],
  ['who_20is_20this_20for_4',['Who is this for?',['../md__2home_2runner_2work_2infix_2infix_2README.html#autotoc_md206',1,'']]],
  ['why_20this_20syntax_5',['4.3 Design Rationale: Why This Syntax?',['../md_signatures.html#autotoc_md174',1,'']]],
  ['wide_6',['System-wide',['../md__2home_2runner_2work_2infix_2infix_2build_2__deps_2doxygen-awesome-css-src_2README.html#autotoc_md39',1,'']]],
  ['width_7',['Width',['../md__2home_2runner_2work_2infix_2infix_2build_2__deps_2doxygen-awesome-css-src_2docs_2tricks.html#tricks-sidebar',1,'Choosing Sidebar Width'],['../md__2home_2runner_2work_2infix_2infix_2build_2__deps_2doxygen-awesome-css-src_2docs_2tricks.html#autotoc_md21',1,'Full Width']]],
  ['width_20types_8',['2.2 Tier 2: Explicit Fixed-Width Types',['../md_signatures.html#autotoc_md165',1,'']]],
  ['windows_20with_20msvc_9',['NMake (Windows with MSVC)',['../md__2home_2runner_2work_2infix_2infix_2INSTALL.html#autotoc_md191',1,'']]],
  ['with_20a_20c_20class_10',['Recipe: Interfacing with a C++ Class',['../md_cookbook.html#autotoc_md93',1,'']]],
  ['with_20complex_20numbers_11',['Recipe: Working with Complex Numbers',['../md_cookbook.html#autotoc_md77',1,'']]],
  ['with_20fetchcontent_12',['CMake with FetchContent',['../md__2home_2runner_2work_2infix_2infix_2build_2__deps_2doxygen-awesome-css-src_2README.html#autotoc_md37',1,'']]],
  ['with_20fixed_20size_20arrays_13',['Recipe: Working with Fixed-Size Arrays',['../md_cookbook.html#autotoc_md67',1,'']]],
  ['with_20gdb_20lldb_14',['Method 2: Live Debugging with GDB/LLDB',['../md_internals.html#autotoc_md147',1,'']]],
  ['with_20graphviz_15',['Diagrams with Graphviz',['../md__2home_2runner_2work_2infix_2infix_2build_2__deps_2doxygen-awesome-css-src_2docs_2tricks.html#tricks-graphviz',1,'']]],
  ['with_20msvc_16',['NMake (Windows with MSVC)',['../md__2home_2runner_2work_2infix_2infix_2INSTALL.html#autotoc_md191',1,'']]],
  ['with_20nested_20ffi_20calls_17',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_cookbook.html#autotoc_md88',1,'']]],
  ['with_20opaque_20pointers_20incomplete_20types_18',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_cookbook.html#autotoc_md66',1,'']]],
  ['with_20other_20languages_19',['Chapter 5: Interoperability with Other Languages',['../md_cookbook.html#autotoc_md91',1,'']]],
  ['with_20other_20systems_20',['4.4 Comparison with Other Systems',['../md_signatures.html#autotoc_md175',1,'']]],
  ['with_20packed_20structs_21',['Recipe: Working with Packed Structs',['../md_cookbook.html#autotoc_md74',1,'']]],
  ['with_20pointers_20to_20arrays_22',['Recipe: Working with Pointers to Arrays',['../md_cookbook.html#autotoc_md76',1,'']]],
  ['with_20simd_20vectors_23',['Recipe: Working with SIMD Vectors',['../md_cookbook.html#autotoc_md78',1,'']]],
  ['with_20the_20signature_20parser_24',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_cookbook.html#autotoc_md70',1,'']]],
  ['with_20tt_20find_5fpackage_20tt_25',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md__2home_2runner_2work_2infix_2infix_2INSTALL.html#autotoc_md195',1,'']]],
  ['with_20tt_20infix_5fdump_5fhex_20tt_26',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_internals.html#autotoc_md146',1,'']]],
  ['with_20unions_27',['Recipe: Working with Unions',['../md_cookbook.html#autotoc_md75',1,'']]],
  ['working_20with_20complex_20numbers_28',['Recipe: Working with Complex Numbers',['../md_cookbook.html#autotoc_md77',1,'']]],
  ['working_20with_20fixed_20size_20arrays_29',['Recipe: Working with Fixed-Size Arrays',['../md_cookbook.html#autotoc_md67',1,'']]],
  ['working_20with_20opaque_20pointers_20incomplete_20types_30',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_cookbook.html#autotoc_md66',1,'']]],
  ['working_20with_20packed_20structs_31',['Recipe: Working with Packed Structs',['../md_cookbook.html#autotoc_md74',1,'']]],
  ['working_20with_20pointers_20to_20arrays_32',['Recipe: Working with Pointers to Arrays',['../md_cookbook.html#autotoc_md76',1,'']]],
  ['working_20with_20simd_20vectors_33',['Recipe: Working with SIMD Vectors',['../md_cookbook.html#autotoc_md78',1,'']]],
  ['working_20with_20unions_34',['Recipe: Working with Unions',['../md_cookbook.html#autotoc_md75',1,'']]],
  ['wrapper_35',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_cookbook.html#autotoc_md79',1,'']]],
  ['write_36',['write',['../structcmd_8h.html#af2a3ea719b83f672637febdd87c36c36',1,'structcmd.h']]],
  ['write_20xor_20execute_20memory_20policy_37',['1. W^X (Write XOR Execute) Memory Policy',['../md__2home_2runner_2work_2infix_2infix_2SECURITY.html#autotoc_md220',1,'']]],
  ['write_20xor_20execute_20w_20x_38',['Write XOR Execute (W^X)',['../md_internals.html#autotoc_md137',1,'']]]
];
