var searchData=
[
  ['w_20x_0',['Write XOR Execute (W^X)',['../md_internals.html#autotoc_md93',1,'']]],
  ['w_20x_20write_20xor_20execute_20memory_20policy_1',['1. W^X (Write XOR Execute) Memory Policy',['../md__2home_2runner_2work_2infix_2infix_2SECURITY.html#autotoc_md176',1,'']]],
  ['way_2',['Recipe: Creating a Stateful Callback (The Modern Way)',['../md_cookbook.html#autotoc_md39',1,'']]],
  ['whitespace_20and_20comments_3',['4.1 Whitespace and Comments',['../md_signatures.html#autotoc_md128',1,'']]],
  ['who_20is_20this_20for_4',['Who is this for?',['../md__2home_2runner_2work_2infix_2infix_2README.html#autotoc_md162',1,'']]],
  ['why_20this_20syntax_5',['4.3 Design Rationale: Why This Syntax?',['../md_signatures.html#autotoc_md130',1,'']]],
  ['width_20types_6',['2.2 Tier 2: Explicit Fixed-Width Types',['../md_signatures.html#autotoc_md121',1,'']]],
  ['windows_20with_20msvc_7',['NMake (Windows with MSVC)',['../md__2home_2runner_2work_2infix_2infix_2INSTALL.html#autotoc_md147',1,'']]],
  ['with_20a_20c_20class_8',['Recipe: Interfacing with a C++ Class',['../md_cookbook.html#autotoc_md49',1,'']]],
  ['with_20complex_20numbers_9',['Recipe: Working with Complex Numbers',['../md_cookbook.html#autotoc_md33',1,'']]],
  ['with_20fixed_20size_20arrays_10',['Recipe: Working with Fixed-Size Arrays',['../md_cookbook.html#autotoc_md23',1,'']]],
  ['with_20gdb_20lldb_11',['Method 2: Live Debugging with GDB/LLDB',['../md_internals.html#autotoc_md103',1,'']]],
  ['with_20msvc_12',['NMake (Windows with MSVC)',['../md__2home_2runner_2work_2infix_2infix_2INSTALL.html#autotoc_md147',1,'']]],
  ['with_20nested_20ffi_20calls_13',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_cookbook.html#autotoc_md44',1,'']]],
  ['with_20opaque_20pointers_20incomplete_20types_14',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_cookbook.html#autotoc_md22',1,'']]],
  ['with_20other_20languages_15',['Chapter 5: Interoperability with Other Languages',['../md_cookbook.html#autotoc_md47',1,'']]],
  ['with_20other_20systems_16',['4.4 Comparison with Other Systems',['../md_signatures.html#autotoc_md131',1,'']]],
  ['with_20packed_20structs_17',['Recipe: Working with Packed Structs',['../md_cookbook.html#autotoc_md30',1,'']]],
  ['with_20pointers_20to_20arrays_18',['Recipe: Working with Pointers to Arrays',['../md_cookbook.html#autotoc_md32',1,'']]],
  ['with_20simd_20vectors_19',['Recipe: Working with SIMD Vectors',['../md_cookbook.html#autotoc_md34',1,'']]],
  ['with_20the_20signature_20parser_20',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_cookbook.html#autotoc_md26',1,'']]],
  ['with_20tt_20find_5fpackage_20tt_21',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md__2home_2runner_2work_2infix_2infix_2INSTALL.html#autotoc_md151',1,'']]],
  ['with_20tt_20infix_5fdump_5fhex_20tt_22',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_internals.html#autotoc_md102',1,'']]],
  ['with_20unions_23',['Recipe: Working with Unions',['../md_cookbook.html#autotoc_md31',1,'']]],
  ['working_20with_20complex_20numbers_24',['Recipe: Working with Complex Numbers',['../md_cookbook.html#autotoc_md33',1,'']]],
  ['working_20with_20fixed_20size_20arrays_25',['Recipe: Working with Fixed-Size Arrays',['../md_cookbook.html#autotoc_md23',1,'']]],
  ['working_20with_20opaque_20pointers_20incomplete_20types_26',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_cookbook.html#autotoc_md22',1,'']]],
  ['working_20with_20packed_20structs_27',['Recipe: Working with Packed Structs',['../md_cookbook.html#autotoc_md30',1,'']]],
  ['working_20with_20pointers_20to_20arrays_28',['Recipe: Working with Pointers to Arrays',['../md_cookbook.html#autotoc_md32',1,'']]],
  ['working_20with_20simd_20vectors_29',['Recipe: Working with SIMD Vectors',['../md_cookbook.html#autotoc_md34',1,'']]],
  ['working_20with_20unions_30',['Recipe: Working with Unions',['../md_cookbook.html#autotoc_md31',1,'']]],
  ['wrapper_31',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_cookbook.html#autotoc_md35',1,'']]],
  ['write_32',['write',['../structcmd_8h.html#af2a3ea719b83f672637febdd87c36c36',1,'structcmd.h']]],
  ['write_20xor_20execute_20memory_20policy_33',['1. W^X (Write XOR Execute) Memory Policy',['../md__2home_2runner_2work_2infix_2infix_2SECURITY.html#autotoc_md176',1,'']]],
  ['write_20xor_20execute_20w_20x_34',['Write XOR Execute (W^X)',['../md_internals.html#autotoc_md93',1,'']]]
];
