name: Inspect macOS Interpreter Entitlements

on:
  workflow_dispatch:

permissions:
  contents: read
  # actions: read is required to list artifacts via the API
  actions: read

jobs:
  inspect:
    runs-on: macos-latest
    steps:
      - name: Start Inspection
        run: echo "Starting entitlement inspection on runner..."

      - name: 1. Inspect System Perl
        run: |
          echo "--- Verifying System Perl (/usr/bin/perl) ---"
          echo "--- [Step 1/2] Displaying full signature info... ---"
          codesign -dv /usr/bin/perl 2>&1 || true
          echo "--- [Step 2/2] Displaying entitlements... ---"
          codesign -d --entitlements - /usr/bin/perl 2>&1
          echo "Exit code of entitlement check: $?"

      - name: 2. Inspect System Python 3
        run: |
          echo "--- Verifying System Python 3 (/usr/bin/python3) ---"
          echo "--- [Step 1/2] Displaying full signature info... ---"
          codesign -dv /usr/bin/python3 2>&1 || true
          echo "--- [Step 2/2] Displaying entitlements... ---"
          codesign -d --entitlements - /usr/bin/python3 2>&1
          echo "Exit code of entitlement check: $?"

      - name: 3. Install and Inspect Homebrew Interpreters
        run: |
          echo "--- Installing Homebrew packages ---"
          brew install perl python

          echo "--- Verifying Homebrew Perl ---"
          PERL_PATH=$(brew --prefix perl)/bin/perl
          echo "Homebrew Perl is at: $PERL_PATH"
          echo "--- [Step 1/2] Displaying full signature info... ---"
          codesign -dv "$PERL_PATH" 2>&1 || true
          echo "--- [Step 2/2] Displaying entitlements... ---"
          codesign -d --entitlements - "$PERL_PATH" 2>&1
          echo "Exit code of entitlement check: $?"

          echo "--- Verifying Homebrew Python 3 ---"
          PYTHON_PATH=$(brew --prefix python)/bin/python3
          echo "Homebrew Python is at: $PYTHON_PATH"
          echo "--- [Step 1/2] Displaying full signature info... ---"
          codesign -dv "$PYTHON_PATH" 2>&1 || true
          echo "--- [Step 2/2] Displaying entitlements... ---"
          codesign -d --entitlements - "$PYTHON_PATH" 2>&1
          echo "Exit code of entitlement check: $?"