name: Doxygen GitHub Pages

on:
  #~ pull_request: ~
  #~ push: ~
  schedule:
    - cron: '42 5 * * 0'
  workflow_dispatch: ~

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Clone Doxygen Awesome CSS theme
        run: git clone --depth 1 https://github.com/jothepro/doxygen-awesome-css.git docs/doxygen-awesome-css

      - name: Generate Doxygen documentation
        # Run doxygen, specifying the path to our Doxyfile.
        run: doxygen docs/Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api/html
          keep_files: true
          destination_dir: ./${{ env.DOXYGEN_OUTPUT_PATH }}
          # The user who will commit the changes
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'docs: Deploy ${{ env.DOXYGEN_OUTPUT_PATH }} documentation'
