var searchData=
[
  ['f90_20tt_0',['Fortran Code (&lt;tt&gt;libfortran_math.f90&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md51',1,'']]],
  ['feature_20detection_20macros_1',['SIMD Feature Detection Macros',['../group__simd__macros.html',1,'']]],
  ['features_2',['features',['..//home/runner/work/infix/infix/README.md#autotoc_md216',1,'Key Features'],['../index.html#features_sec',1,'Key Features']]],
  ['features_20polish_20strong_3',['&lt;strong&gt;Low Priority: Advanced Features &amp; Polish&lt;/strong&gt;',['../md_TODO.html#autotoc_md244',1,'']]],
  ['ffi_20calls_4',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_docs_2cookbook.html#autotoc_md41',1,'']]],
  ['ffi_20cookbook_5',['The &lt;tt&gt;infix&lt;/tt&gt; FFI Cookbook',['../md_docs_2cookbook.html',1,'']]],
  ['ffi_20library_6',['ffi library',['../md_CONTRIBUTING.html',1,'Contributing to the infix FFI Library'],['../index.html',1,'Infix FFI Library']]],
  ['ffi_20signature_20format_20specification_20v1_200_7',['FFI Signature Format Specification v1.0',['../md_docs_2signatures.html',1,'']]],
  ['ffi_20strong_8',['&lt;strong&gt;Project Roadmap: infix FFI&lt;/strong&gt;',['../md_TODO.html',1,'']]],
  ['ffi_3a_20internals_20documentation_9',['infix FFI: Internals Documentation',['../md_docs_2internals.html',1,'']]],
  ['final_5fmultiply_5fhandler_10',['final_multiply_handler',['../303__advanced_8c.html#a9593dfbf5450b75b6915dd41944df4ad',1,'303_advanced.c']]],
  ['find_5fchar_5fin_5fstring_11',['find_char_in_string',['../201__basic_8c.html#a021325335442088553d22be0cd27cf58',1,'201_basic.c']]],
  ['find_5fpackage_20tt_12',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md_INSTALL.html#autotoc_md206',1,'']]],
  ['first_20signature_20system_13',['1.3 Our Solution: A Human-First Signature System',['../md_docs_2signatures.html#autotoc_md168',1,'']]],
  ['fixed_20size_20arrays_14',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md22',1,'']]],
  ['fixed_20width_20types_15',['2.2 Tier 2: Explicit Fixed-Width Types',['../md_docs_2signatures.html#autotoc_md172',1,'']]],
  ['float_5fcallback_5fhandler_16',['float_callback_handler',['../301__primitives_8c.html#ad80f5c82da708830d5001239d52010db',1,'301_primitives.c']]],
  ['floating_20point_20aggregates_20hfa_17',['Deep Dive: AArch64 Homogeneous Floating-point Aggregates (HFA)',['../md_docs_2internals.html#autotoc_md113',1,'']]],
  ['flow_18',['Trampoline Generation Flow',['../md_docs_2internals.html#autotoc_md104',1,'']]],
  ['for_19',['Who is this for?',['..//home/runner/work/infix/infix/README.md#autotoc_md217',1,'']]],
  ['for_20a_20wrapper_20',['Recipe: Introspecting a Trampoline for a Wrapper',['../md_docs_2cookbook.html#autotoc_md33',1,'']]],
  ['for_20advanced_20data_20types_21',['4.5 Rationale for Advanced Data Types',['../md_docs_2signatures.html#autotoc_md185',1,'']]],
  ['for_20cross_20platform_20fuzzing_22',['for cross platform fuzzing',['../md_docs_2internals.html#autotoc_md151',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing'],['../md_docs_2internals.html#autotoc_md135',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing']]],
  ['for_20dynamic_20data_20marshalling_23',['Powerful Introspection for Dynamic Data Marshalling',['..//home/runner/work/infix/infix/README.md#autotoc_md223',1,'']]],
  ['for_20freed_20trampolines_24',['Guard Pages for Freed Trampolines',['../md_docs_2internals.html#autotoc_md101',1,'']]],
  ['for_20maintainers_25',['3. Packaging &lt;tt&gt;infix&lt;/tt&gt; (For Maintainers)',['../md_INSTALL.html#autotoc_md212',1,'']]],
  ['for_20safety_26',['The Self-Contained Object Model: Trading Memory for Safety',['../md_docs_2internals.html#autotoc_md136',1,'']]],
  ['for_20tooling_20and_20mental_20modeling_27',['3.4 Benefits for Tooling and Mental Modeling',['../md_docs_2signatures.html#autotoc_md179',1,'']]],
  ['for_20tt_20qsort_20tt_28',['Recipe: Creating a Stateless Callback for &lt;tt&gt;qsort&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md36',1,'']]],
  ['format_20specification_20v1_200_29',['FFI Signature Format Specification v1.0',['../md_docs_2signatures.html',1,'']]],
  ['fortran_30',['Fortran',['../md_docs_2cookbook.html#autotoc_md50',1,'']]],
  ['fortran_20code_20tt_20libfortran_5fmath_20f90_20tt_31',['Fortran Code (&lt;tt&gt;libfortran_math.f90&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md51',1,'']]],
  ['forward_20call_20trampoline_32',['Forward Call Trampoline',['../md_docs_2internals.html#autotoc_md105',1,'']]],
  ['forward_20calls_33',['Chapter 1: The Basics (Forward Calls)',['../md_docs_2cookbook.html#autotoc_md18',1,'']]],
  ['forward_20trampoline_20introspection_20api_34',['Forward Trampoline Introspection API',['../group__forward__introspection__api.html',1,'']]],
  ['forward_5fvariadic_5fchecker_35',['forward_variadic_checker',['../402__variadic__functions_8c.html#ae984df7920796a4871aeec5b6f167b48',1,'402_variadic_functions.c']]],
  ['foundation_20stability_20strong_36',['&lt;strong&gt;High Priority: Foundation &amp; Stability&lt;/strong&gt;',['../md_TODO.html#autotoc_md242',1,'']]],
  ['four_20pillars_20of_20a_20language_20binding_37',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md82',1,'']]],
  ['free_20prevention_20guard_20pages_38',['2. Use-After-Free Prevention (Guard Pages)',['../md_SECURITY.html#autotoc_md236',1,'']]],
  ['freed_20trampolines_39',['Guard Pages for Freed Trampolines',['../md_docs_2internals.html#autotoc_md101',1,'']]],
  ['from_20a_20function_40',['Recipe: Receiving a Struct from a Function',['../md_docs_2cookbook.html#autotoc_md28',1,'']]],
  ['from_20source_41',['1. Building &lt;tt&gt;infix&lt;/tt&gt; from Source',['../md_INSTALL.html#autotoc_md191',1,'']]],
  ['func_5fptr_5finfo_42',['func_ptr_info',['../group__high__level__api.html#ga2a2d9a8c127bba88a5da75433005bdfb',1,'infix_type_t::func_ptr_info'],['../group__high__level__api.html#gad6f74fc69d9df9ad2f239b1bd101845b',1,'infix_type_t::@0::func_ptr_info']]],
  ['function_43',['function',['../md_docs_2cookbook.html#autotoc_md19',1,'Recipe: Calling a Simple C Function'],['../md_docs_2cookbook.html#autotoc_md28',1,'Recipe: Receiving a Struct from a Function']]],
  ['function_20pointer_44',['Recipe: Receiving and Calling a Function Pointer',['../md_docs_2cookbook.html#autotoc_md42',1,'']]],
  ['function_20pointer_20syntax_45',['Pitfall: Function Pointer Syntax',['../md_docs_2cookbook.html#autotoc_md77',1,'']]],
  ['functions_20like_20tt_20printf_20tt_46',['Recipe: Calling Variadic Functions like &lt;tt&gt;printf&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md39',1,'']]],
  ['fuzz_5fabi_2ec_47',['fuzz_abi.c',['../fuzz__abi_8c.html',1,'']]],
  ['fuzz_5fhelpers_2ec_48',['fuzz_helpers.c',['../fuzz__helpers_8c.html',1,'']]],
  ['fuzz_5fhelpers_2eh_49',['fuzz_helpers.h',['../fuzz__helpers_8h.html',1,'']]],
  ['fuzz_5fregression_5fhelpers_2eh_50',['fuzz_regression_helpers.h',['../fuzz__regression__helpers_8h.html',1,'']]],
  ['fuzz_5fsignature_2ec_51',['fuzz_signature.c',['../fuzz__signature_8c.html',1,'']]],
  ['fuzz_5ftrampoline_2ec_52',['fuzz_trampoline.c',['../fuzz__trampoline_8c.html',1,'']]],
  ['fuzz_5ftypes_2ec_53',['fuzz_types.c',['../fuzz__types_8c.html',1,'']]],
  ['fuzzer_5finput_54',['fuzzer_input',['../structfuzzer__input.html',1,'']]],
  ['fuzzer_5ftarget_5ft_55',['fuzzer_target_t',['../850__regression__cases_8c.html#a069f203eb4bd59c4b6e646ea3cef8c26',1,'850_regression_cases.c']]],
  ['fuzzing_56',['fuzzing',['../md_SECURITY.html#autotoc_md239',1,'5. Continuous Security Validation (Fuzzing)'],['../md_docs_2internals.html#autotoc_md151',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing'],['../md_docs_2internals.html#autotoc_md135',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing']]],
  ['fuzzing_20targets_57',['Fuzzing Targets',['../fuzz__signature_8c.html#autotoc_md186',1,'']]]
];
