var searchData=
[
  ['w_20x_0',['Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md99',1,'']]],
  ['w_20x_20write_20xor_20execute_20memory_20policy_1',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md230',1,'']]],
  ['way_2',['Recipe: Creating a Stateful Callback (The Modern Way)',['../md_docs_2cookbook.html#autotoc_md36',1,'']]],
  ['whitespace_20and_20comments_3',['4.1 Whitespace and Comments',['../md_docs_2signatures.html#autotoc_md179',1,'']]],
  ['why_20this_20syntax_4',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md181',1,'']]],
  ['width_20types_5',['2.2 Tier 2: Explicit Fixed-Width Types',['../md_docs_2signatures.html#autotoc_md170',1,'']]],
  ['will_20run_20and_20print_20the_20address_6',['Your program will run and print the address',['../md_docs_2internals.html#autotoc_md118',1,'']]],
  ['windbg_20windows_7',['Method 3: Live Debugging with WinDbg (Windows)',['../md_docs_2internals.html#autotoc_md123',1,'']]],
  ['windows_8',['Method 3: Live Debugging with WinDbg (Windows)',['../md_docs_2internals.html#autotoc_md123',1,'']]],
  ['windows_20type_20definitions_9',['Common Windows Type Definitions',['../md_docs_2internals.html#autotoc_md127',1,'']]],
  ['windows_20with_20msvc_10',['NMake (Windows with MSVC)',['../md_INSTALL.html#autotoc_md200',1,'']]],
  ['windows_20x64_20by_20reference_20rule_11',['Deep Dive: Windows x64 By-Reference Rule',['../md_docs_2internals.html#autotoc_md111',1,'']]],
  ['with_20a_20c_20class_12',['Recipe: Interfacing with a C++ Class',['../md_docs_2cookbook.html#autotoc_md45',1,'']]],
  ['with_20complex_20numbers_13',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md32',1,'']]],
  ['with_20fixed_20size_20arrays_14',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md22',1,'']]],
  ['with_20gdb_20linux_20macos_15',['Method 2: Live Debugging with GDB (Linux/macOS)',['../md_docs_2internals.html#autotoc_md117',1,'']]],
  ['with_20msvc_16',['NMake (Windows with MSVC)',['../md_INSTALL.html#autotoc_md200',1,'']]],
  ['with_20nested_20ffi_20calls_17',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_docs_2cookbook.html#autotoc_md40',1,'']]],
  ['with_20opaque_20pointers_20incomplete_20types_18',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md21',1,'']]],
  ['with_20other_20languages_19',['Chapter 5: Interoperability with Other Languages',['../md_docs_2cookbook.html#autotoc_md43',1,'']]],
  ['with_20other_20systems_20',['4.4 Comparison with Other Systems',['../md_docs_2signatures.html#autotoc_md182',1,'']]],
  ['with_20packed_20structs_21',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md29',1,'']]],
  ['with_20pointers_20to_20arrays_22',['Recipe: Working with Pointers to Arrays',['../md_docs_2cookbook.html#autotoc_md31',1,'']]],
  ['with_20the_20signature_20parser_23',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md25',1,'']]],
  ['with_20tt_20find_5fpackage_20tt_24',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md_INSTALL.html#autotoc_md204',1,'']]],
  ['with_20tt_20infix_5fdump_5fhex_20tt_25',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_docs_2internals.html#autotoc_md116',1,'']]],
  ['with_20unions_26',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md30',1,'']]],
  ['with_20windbg_20windows_27',['Method 3: Live Debugging with WinDbg (Windows)',['../md_docs_2internals.html#autotoc_md123',1,'']]],
  ['with_20xmake_20recommended_28',['Quick Build with xmake (Recommended)',['..//home/runner/work/infix/infix/README.md#autotoc_md216',1,'']]],
  ['working_20with_20complex_20numbers_29',['Recipe: Working with Complex Numbers',['../md_docs_2cookbook.html#autotoc_md32',1,'']]],
  ['working_20with_20fixed_20size_20arrays_30',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md22',1,'']]],
  ['working_20with_20opaque_20pointers_20incomplete_20types_31',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md21',1,'']]],
  ['working_20with_20packed_20structs_32',['Recipe: Working with Packed Structs',['../md_docs_2cookbook.html#autotoc_md29',1,'']]],
  ['working_20with_20pointers_20to_20arrays_33',['Recipe: Working with Pointers to Arrays',['../md_docs_2cookbook.html#autotoc_md31',1,'']]],
  ['working_20with_20unions_34',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md30',1,'']]],
  ['write_20xor_20execute_20memory_20policy_35',['1. W^X (Write XOR Execute) Memory Policy',['../md_SECURITY.html#autotoc_md230',1,'']]],
  ['write_20xor_20execute_20w_20x_36',['Write XOR Execute (W^X)',['../md_docs_2internals.html#autotoc_md99',1,'']]]
];
