var searchData=
[
  ['table_20of_20contents_0',['Table of Contents',['../md_docs_2cookbook.html#autotoc_md16',1,'']]],
  ['tables_20for_20cross_20platform_20fuzzing_1',['tables for cross platform fuzzing',['../md_docs_2internals.html#autotoc_md146',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing'],['../md_docs_2internals.html#autotoc_md131',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing']]],
  ['target_2',['target',['../structregression__test__case__t.html#af90a3e3c9b148c3d159737f30829fb7b',1,'regression_test_case_t']]],
  ['target_5fsignature_5fparser_3',['TARGET_SIGNATURE_PARSER',['../850__regression__cases_8c.html#a069f203eb4bd59c4b6e646ea3cef8c26ac1087e2263e08e0f1e32f593dd317883',1,'850_regression_cases.c']]],
  ['target_5ftype_5fgenerator_4',['TARGET_TYPE_GENERATOR',['../850__regression__cases_8c.html#a069f203eb4bd59c4b6e646ea3cef8c26a2246791a3ac8f7a85236a7ef499a89d3',1,'850_regression_cases.c']]],
  ['targets_5',['Fuzzing Targets',['../fuzz__signature_8c.html#autotoc_md165',1,'']]],
  ['techniques_6',['Chapter 4: Advanced Techniques',['../md_docs_2cookbook.html#autotoc_md36',1,'']]],
  ['test_7',['How to Add a New Regression Test',['../850__regression__cases_8c.html#autotoc_md227',1,'']]],
  ['test_5fprimitive_8',['TEST_PRIMITIVE',['../001__primitives_8c.html#a7b9434662a6bdbb629296e28900aaf75',1,'001_primitives.c']]],
  ['testing_9',['Step 5: Testing',['../md_docs_2porting.html#autotoc_md156',1,'']]],
  ['teststruct_10',['TestStruct',['../structTestStruct.html',1,'']]],
  ['testunion_11',['TestUnion',['../unionTestUnion.html',1,'']]],
  ['the_20abi_20abstraction_20layer_20and_20trampoline_20generator_20tt_20trampoline_20c_20tt_12',['5. The ABI Abstraction Layer and Trampoline Generator (&lt;tt&gt;trampoline.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md99',1,'']]],
  ['the_20abi_20specification_13',['Step 2: Implement the ABI Specification',['../md_docs_2porting.html#autotoc_md153',1,'']]],
  ['the_20address_14',['Your program will run and print the address',['../md_docs_2internals.html#autotoc_md115',1,'']]],
  ['the_20alternative_3a_20the_20call_20vm_20interpreter_20model_20e_20g_20tt_20dyncall_20tt_15',['The Alternative: The Call VM / Interpreter Model (e.g., &lt;tt&gt;dyncall&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md137',1,'']]],
  ['the_20arena_20based_20manual_20api_16',['the arena based manual api',['../md_docs_2internals.html#autotoc_md129',1,'Memory Safety by Default: The Arena-Based Manual API'],['../md_docs_2internals.html#autotoc_md144',1,'Memory Safety by Default: The Arena-Based Manual API']]],
  ['the_20basics_20forward_20calls_17',['Chapter 1: The Basics (Forward Calls)',['../md_docs_2cookbook.html#autotoc_md18',1,'']]],
  ['the_20breakpoint_18',['Now, set the breakpoint',['../md_docs_2internals.html#autotoc_md116',1,'']]],
  ['the_20callback_20bridge_19',['4. Implementing the Callback Bridge',['../md_docs_2cookbook.html#autotoc_md82',1,'']]],
  ['the_20core_20api_20tt_20infix_5ftype_5fcreate_5f_20tt_20tt_20infix_5fforward_5fcreate_5fmanual_20tt_20',['The Core API (&lt;tt&gt;infix_type_create_*&lt;/tt&gt;, &lt;tt&gt;infix_forward_create_manual&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md90',1,'']]],
  ['the_20debugging_20guide_21',['The Debugging Guide',['../md_docs_2internals.html#autotoc_md111',1,'']]],
  ['the_20four_20pillars_20of_20a_20language_20binding_22',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md78',1,'']]],
  ['the_20infix_20ffi_20library_23',['Contributing to the infix FFI Library',['../md_CONTRIBUTING.html',1,'']]],
  ['the_20instruction_20emitters_24',['Step 3: Implement the Instruction Emitters',['../md_docs_2porting.html#autotoc_md154',1,'']]],
  ['the_20jit_20compiler_20vs_20the_20call_20vm_25',['Core Design Philosophy: The JIT Compiler vs. The Call VM',['../md_docs_2internals.html#autotoc_md136',1,'']]],
  ['the_20manual_20api_20advanced_26',['The Manual API (Advanced)',['..//home/runner/work/infix/infix/README.md#autotoc_md201',1,'']]],
  ['the_20modern_20way_27',['Recipe: Creating a Stateful Callback (The Modern Way)',['../md_docs_2cookbook.html#autotoc_md35',1,'']]],
  ['the_20new_20abi_28',['Step 4: Integrate the New ABI',['../md_docs_2porting.html#autotoc_md155',1,'']]],
  ['the_20power_20of_20callbacks_20reverse_20calls_29',['Chapter 3: The Power of Callbacks (Reverse Calls)',['../md_docs_2cookbook.html#autotoc_md33',1,'']]],
  ['the_20power_20of_20the_20universal_20context_30',['the power of the universal context',['../md_docs_2internals.html#autotoc_md145',1,'Callbacks: The Power of the Universal Context'],['../md_docs_2internals.html#autotoc_md130',1,'Callbacks: The Power of the Universal Context']]],
  ['the_20signature_20api_31',['Recipe: Working with Packed Structs via the Signature API',['../md_docs_2cookbook.html#autotoc_md29',1,'']]],
  ['the_20signature_20api_20recommended_32',['The Signature API (Recommended)',['..//home/runner/work/infix/infix/README.md#autotoc_md200',1,'']]],
  ['the_20signature_20api_20tt_20infix_5fforward_5fcreate_20tt_20tt_20infix_5freverse_5fcreate_20tt_33',['The Signature API (&lt;tt&gt;infix_forward_create&lt;/tt&gt;, &lt;tt&gt;infix_reverse_create&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md91',1,'']]],
  ['the_20signature_20parser_34',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md25',1,'']]],
  ['the_20signature_20parser_20tt_20signature_20c_20tt_35',['2. The Signature Parser (&lt;tt&gt;signature.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md92',1,'']]],
  ['the_20tt_20infix_20tt_20approach_3a_20the_20jit_20compiler_20model_36',['The &lt;tt&gt;infix&lt;/tt&gt; Approach: The JIT Compiler Model',['../md_docs_2internals.html#autotoc_md138',1,'']]],
  ['the_20tt_20infix_20tt_20ffi_20cookbook_37',['The &lt;tt&gt;infix&lt;/tt&gt; FFI Cookbook',['../md_docs_2cookbook.html',1,'']]],
  ['the_20tt_20infix_20tt_20signature_20language_20reference_38',['The &lt;tt&gt;infix&lt;/tt&gt; Signature Language Reference',['../md_docs_2signatures.html',1,'']]],
  ['the_20tt_20infix_5f_20tt_20prefix_39',['the tt infix_ tt prefix',['../md_docs_2internals.html#autotoc_md128',1,'API Naming: The &lt;tt&gt;infix_&lt;/tt&gt; Prefix'],['../md_docs_2internals.html#autotoc_md143',1,'API Naming: The &lt;tt&gt;infix_&lt;/tt&gt; Prefix']]],
  ['the_20type_20system_20tt_20types_20c_20tt_40',['3. The Type System (&lt;tt&gt;types.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md94',1,'']]],
  ['the_20unity_20build_41',['the unity build',['../md_docs_2internals.html#autotoc_md103',1,'A Note on the &quot;Unity&quot; Build'],['../md_docs_2internals.html#autotoc_md142',1,'The Unity Build']]],
  ['the_20universal_20context_42',['the universal context',['../md_docs_2internals.html#autotoc_md130',1,'Callbacks: The Power of the Universal Context'],['../md_docs_2internals.html#autotoc_md145',1,'Callbacks: The Power of the Universal Context']]],
  ['the_20universal_20principle_3a_20the_20c_20abi_43',['The Universal Principle: The C ABI',['../md_docs_2cookbook.html#autotoc_md43',1,'']]],
  ['to_20a_20new_20platform_44',['Porting &lt;tt&gt;infix&lt;/tt&gt; to a New Platform',['../md_docs_2porting.html',1,'']]],
  ['to_20add_20a_20new_20regression_20test_45',['How to Add a New Regression Test',['../850__regression__cases_8c.html#autotoc_md227',1,'']]],
  ['to_20arrays_46',['Recipe: Working with Pointers to Arrays',['../md_docs_2cookbook.html#autotoc_md31',1,'']]],
  ['to_20contribute_47',['How to Contribute',['../md_CONTRIBUTING.html#autotoc_md12',1,'']]],
  ['to_20the_20infix_20ffi_20library_48',['Contributing to the infix FFI Library',['../md_CONTRIBUTING.html',1,'']]],
  ['total_5fstack_5falloc_49',['total_stack_alloc',['../structinfix__call__frame__layout.html#a743d543342256cf155458951d48c613e',1,'infix_call_frame_layout::total_stack_alloc'],['../structinfix__reverse__call__frame__layout.html#aedb51aeb6365d359bcb27d1e9920a0d8',1,'infix_reverse_call_frame_layout::total_stack_alloc']]],
  ['trampoline_50',['Forward Call Trampoline',['../md_docs_2internals.html#autotoc_md101',1,'']]],
  ['trampoline_20c_20tt_51',['5. The ABI Abstraction Layer and Trampoline Generator (&lt;tt&gt;trampoline.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md99',1,'']]],
  ['trampoline_20caching_52',['2. Trampoline Caching',['../md_docs_2cookbook.html#autotoc_md80',1,'']]],
  ['trampoline_20callbacks_53',['Reverse Call Trampoline (Callbacks)',['../md_docs_2internals.html#autotoc_md102',1,'']]],
  ['trampoline_20generation_20flow_54',['Trampoline Generation Flow',['../md_docs_2internals.html#autotoc_md100',1,'']]],
  ['trampoline_20generator_20tt_20trampoline_20c_20tt_55',['5. The ABI Abstraction Layer and Trampoline Generator (&lt;tt&gt;trampoline.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md99',1,'']]],
  ['trampoline_2ec_56',['trampoline.c',['../trampoline_8c.html',1,'']]],
  ['trampolines_57',['trampolines',['../md_docs_2cookbook.html#autotoc_md70',1,'Best Practice: Caching Trampolines'],['../md_docs_2internals.html#autotoc_md97',1,'Guard Pages for Freed Trampolines']]],
  ['troubleshooting_58',['Chapter 8: Common Pitfalls &amp; Troubleshooting',['../md_docs_2cookbook.html#autotoc_md72',1,'']]],
  ['tt_20args_20tt_59',['Mistake: Passing a Value Instead of a Pointer in &lt;tt&gt;args[]&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md73',1,'']]],
  ['tt_20dyncall_20tt_60',['The Alternative: The Call VM / Interpreter Model (e.g., &lt;tt&gt;dyncall&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md137',1,'']]],
  ['tt_20executor_20c_20tt_61',['4. Executable Memory Management and Security (&lt;tt&gt;executor.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md95',1,'']]],
  ['tt_20find_5fpackage_20tt_62',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md_INSTALL.html#autotoc_md185',1,'']]],
  ['tt_20infix_20h_20tt_63',['Step 1: Platform Detection (&lt;tt&gt;infix.h&lt;/tt&gt;)',['../md_docs_2porting.html#autotoc_md152',1,'']]],
  ['tt_20infix_20tt_64',['Building and Integrating &lt;tt&gt;infix&lt;/tt&gt;',['../md_INSTALL.html',1,'']]],
  ['tt_20infix_20tt_20approach_3a_20the_20jit_20compiler_20model_65',['The &lt;tt&gt;infix&lt;/tt&gt; Approach: The JIT Compiler Model',['../md_docs_2internals.html#autotoc_md138',1,'']]],
  ['tt_20infix_20tt_20ffi_20cookbook_66',['The &lt;tt&gt;infix&lt;/tt&gt; FFI Cookbook',['../md_docs_2cookbook.html',1,'']]],
  ['tt_20infix_20tt_20for_20maintainers_67',['3. Packaging &lt;tt&gt;infix&lt;/tt&gt; (For Maintainers)',['../md_INSTALL.html#autotoc_md190',1,'']]],
  ['tt_20infix_20tt_20from_20source_68',['1. Building &lt;tt&gt;infix&lt;/tt&gt; from Source',['../md_INSTALL.html#autotoc_md170',1,'']]],
  ['tt_20infix_20tt_20into_20your_20project_69',['2. Integrating &lt;tt&gt;infix&lt;/tt&gt; into Your Project',['../md_INSTALL.html#autotoc_md184',1,'']]],
  ['tt_20infix_20tt_20signature_20language_20reference_70',['The &lt;tt&gt;infix&lt;/tt&gt; Signature Language Reference',['../md_docs_2signatures.html',1,'']]],
  ['tt_20infix_20tt_20signature_20mismatch_71',['Mistake: &lt;tt&gt;infix&lt;/tt&gt; Signature Mismatch',['../md_docs_2cookbook.html#autotoc_md74',1,'']]],
  ['tt_20infix_20tt_20to_20a_20new_20platform_72',['Porting &lt;tt&gt;infix&lt;/tt&gt; to a New Platform',['../md_docs_2porting.html',1,'']]],
  ['tt_20infix_5f_20tt_20prefix_73',['tt infix_ tt prefix',['../md_docs_2internals.html#autotoc_md143',1,'API Naming: The &lt;tt&gt;infix_&lt;/tt&gt; Prefix'],['../md_docs_2internals.html#autotoc_md128',1,'API Naming: The &lt;tt&gt;infix_&lt;/tt&gt; Prefix']]],
  ['tt_20infix_5fdump_5fhex_20tt_74',['Method 1: Static Analysis with &lt;tt&gt;infix_dump_hex&lt;/tt&gt;',['../md_docs_2internals.html#autotoc_md113',1,'']]],
  ['tt_20infix_5fforward_5fcreate_20tt_20tt_20infix_5freverse_5fcreate_20tt_75',['The Signature API (&lt;tt&gt;infix_forward_create&lt;/tt&gt;, &lt;tt&gt;infix_reverse_create&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md91',1,'']]],
  ['tt_20infix_5ftype_5fcreate_5f_20tt_20tt_20infix_5fforward_5fcreate_5fmanual_20tt_76',['The Core API (&lt;tt&gt;infix_type_create_*&lt;/tt&gt;, &lt;tt&gt;infix_forward_create_manual&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md90',1,'']]],
  ['tt_20libasm_5fmath_20asm_20tt_77',['NASM Code (&lt;tt&gt;libasm_math.asm&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md64',1,'']]],
  ['tt_20libd_5fmath_20d_20tt_78',['D Code (&lt;tt&gt;libd_math.d&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['tt_20libfortran_5fmath_20f90_20tt_79',['Fortran Code (&lt;tt&gt;libfortran_math.f90&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md49',1,'']]],
  ['tt_20libgo_5fmath_20go_20tt_80',['Go Code (&lt;tt&gt;libgo_math.go&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md55',1,'']]],
  ['tt_20librust_5fmath_20rs_20tt_81',['Rust Code (&lt;tt&gt;librust_math.rs&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md46',1,'']]],
  ['tt_20libswift_5fmath_20swift_20tt_82',['Swift Code (&lt;tt&gt;libswift_math.swift&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md58',1,'']]],
  ['tt_20libzig_5fmath_20zig_20tt_83',['Zig Code (&lt;tt&gt;libzig_math.zig&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md52',1,'']]],
  ['tt_20main_5fasm_20c_20tt_84',['infix C Code (&lt;tt&gt;main_asm.c&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md65',1,'']]],
  ['tt_20main_5fd_20c_20tt_85',['infix C Code (&lt;tt&gt;main_d.c&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['tt_20main_5ffortran_20c_20tt_86',['infix C Code (&lt;tt&gt;main_fortran.c&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md50',1,'']]],
  ['tt_20main_5fgo_20c_20tt_87',['infix C Code (&lt;tt&gt;main_go.c&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md56',1,'']]],
  ['tt_20main_5frust_20c_20tt_88',['infix C Code (&lt;tt&gt;main_rust.c&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md47',1,'']]],
  ['tt_20main_5fswift_20c_20tt_89',['infix C Code (&lt;tt&gt;main_swift.c&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md59',1,'']]],
  ['tt_20main_5fzig_20c_20tt_90',['infix C Code (&lt;tt&gt;main_zig.c&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md53',1,'']]],
  ['tt_20printf_20tt_91',['Recipe: Calling Variadic Functions like &lt;tt&gt;printf&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md37',1,'']]],
  ['tt_20qsort_20tt_92',['Recipe: Creating a Stateless Callback for &lt;tt&gt;qsort&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md34',1,'']]],
  ['tt_20signature_20c_20tt_93',['2. The Signature Parser (&lt;tt&gt;signature.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md92',1,'']]],
  ['tt_20trampoline_20c_20tt_94',['5. The ABI Abstraction Layer and Trampoline Generator (&lt;tt&gt;trampoline.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md99',1,'']]],
  ['tt_20types_20c_20tt_95',['3. The Type System (&lt;tt&gt;types.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md94',1,'']]],
  ['type_96',['type',['../structinfix__arg__location.html#a4f53bb713bc5749863d8ba2633b74604',1,'infix_arg_location::type'],['../group__high__level__api.html#gaa89e6621da98f5115dcc807599c4ac77',1,'infix_struct_member_t::type']]],
  ['type_20constructors_20and_20modifiers_97',['Type Constructors and Modifiers',['../md_docs_2signatures.html#autotoc_md162',1,'']]],
  ['type_20definitions_98',['Common Windows Type Definitions',['../md_docs_2internals.html#autotoc_md124',1,'']]],
  ['type_20mapping_20signature_20string_20generation_99',['1. Type Mapping -&gt; Signature String Generation',['../md_docs_2cookbook.html#autotoc_md79',1,'']]],
  ['type_20reference_100',['A Cross-Language Type Reference',['../md_docs_2internals.html#autotoc_md123',1,'']]],
  ['type_20system_20tt_20types_20c_20tt_101',['3. The Type System (&lt;tt&gt;types.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md94',1,'']]],
  ['types_102',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md21',1,'']]],
  ['types_20c_20tt_103',['3. The Type System (&lt;tt&gt;types.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md94',1,'']]],
  ['types_2ec_104',['types.c',['../types_8c.html',1,'']]],
  ['types_2eh_105',['types.h',['../eg_2cookbook_2lib_2types_8h.html',1,'(Global Namespace)'],['../t_2include_2types_8h.html',1,'(Global Namespace)']]]
];
