var searchData=
[
  ['language_20binding_0',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md81',1,'']]],
  ['language_20bindings_1',['Chapter 9: Building Language Bindings',['../md_docs_2cookbook.html#autotoc_md80',1,'']]],
  ['language_20type_20reference_2',['A Cross-Language Type Reference',['../md_docs_2internals.html#autotoc_md126',1,'']]],
  ['languages_3',['Chapter 5: Interoperability with Other Languages',['../md_docs_2cookbook.html#autotoc_md43',1,'']]],
  ['large_20structs_20passed_20by_20reference_4',['Recipe: Large Structs Passed by Reference',['../md_docs_2cookbook.html#autotoc_md27',1,'']]],
  ['large_5fstack_5fcallee_5',['large_stack_callee',['../401__large__stack_8c.html#a8d9b25f0d708a936741592612cc6abfa',1,'401_large_stack.c']]],
  ['large_5fstruct_5fpass_5fhandler_6',['large_struct_pass_handler',['../302__aggregates_8c.html#ac84a68db4e3aae7e761f6ed7196ce3e2',1,'302_aggregates.c']]],
  ['large_5fstruct_5freturn_5fhandler_7',['large_struct_return_handler',['../302__aggregates_8c.html#a534b99cfc4e2eb58aa6b1912be1f7c62',1,'302_aggregates.c']]],
  ['largedata_8',['LargeData',['../structLargeData.html',1,'']]],
  ['largestruct_9',['LargeStruct',['../structLargeStruct.html',1,'']]],
  ['last_5ferror_10',['last_error',['../structparser__state.html#aec169142e1e627e92491cad871bf677a',1,'parser_state']]],
  ['layer_20and_20trampoline_20generator_20tt_20trampoline_20c_20tt_11',['5. The ABI Abstraction Layer and Trampoline Generator (&lt;tt&gt;trampoline.c&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md102',1,'']]],
  ['layers_3a_20core_20vs_20signature_12',['1. API Layers: Core vs. Signature',['../md_docs_2internals.html#autotoc_md92',1,'']]],
  ['learn_20more_13',['Learn More',['..//home/runner/work/infix/infix/README.md#autotoc_md221',1,'']]],
  ['legal_14',['legal',['..//home/runner/work/infix/infix/README.md#autotoc_md222',1,'License &amp; Legal'],['../md_docs_2cookbook.html#autotoc_md87',1,'License and Legal'],['../md_docs_2porting.html#autotoc_md161',1,'License and Legal'],['../md_docs_2internals.html#autotoc_md152',1,'License and Legal']]],
  ['level_20signature_20api_15',['High-Level Signature API',['../group__high__level__api.html',1,'']]],
  ['libasm_5fmath_20asm_20tt_16',['NASM Code (&lt;tt&gt;libasm_math.asm&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md65',1,'']]],
  ['libd_5fmath_20d_20tt_17',['D Code (&lt;tt&gt;libd_math.d&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['libfortran_5fmath_20f90_20tt_18',['Fortran Code (&lt;tt&gt;libfortran_math.f90&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md50',1,'']]],
  ['libgo_5fmath_20go_20tt_19',['Go Code (&lt;tt&gt;libgo_math.go&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md56',1,'']]],
  ['libraries_20',['libraries',['../md_docs_2cookbook.html#autotoc_md67',1,'Chapter 6: Calling System Libraries'],['../md_docs_2cookbook.html#autotoc_md68',1,'Recipe: Calling Native System Libraries']]],
  ['library_21',['library',['../md_CONTRIBUTING.html',1,'Contributing to the infix FFI Library'],['../index.html',1,'Infix FFI Library'],['..//home/runner/work/infix/infix/README.md#autotoc_md213',1,'Quick Start: Calling a Shared Library']]],
  ['librust_5fmath_20rs_20tt_22',['Rust Code (&lt;tt&gt;librust_math.rs&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md47',1,'']]],
  ['libswift_5fmath_20swift_20tt_23',['Swift Code (&lt;tt&gt;libswift_math.swift&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md59',1,'']]],
  ['libzig_5fmath_20zig_20tt_24',['Zig Code (&lt;tt&gt;libzig_math.zig&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md53',1,'']]],
  ['license_25',['license',['..//home/runner/work/infix/infix/README.md#autotoc_md223',1,'Code License'],['..//home/runner/work/infix/infix/README.md#autotoc_md224',1,'Documentation License']]],
  ['license_20and_20legal_26',['license and legal',['../md_docs_2cookbook.html#autotoc_md87',1,'License and Legal'],['../md_docs_2internals.html#autotoc_md152',1,'License and Legal'],['../md_docs_2porting.html#autotoc_md161',1,'License and Legal']]],
  ['license_20legal_27',['License &amp; Legal',['..//home/runner/work/infix/infix/README.md#autotoc_md222',1,'']]],
  ['licensing_28',['Licensing',['../index.html#license_sec',1,'']]],
  ['lifetimes_29',['3. Managing Memory &amp; Object Lifetimes',['../md_docs_2cookbook.html#autotoc_md84',1,'']]],
  ['like_20tt_20printf_20tt_30',['Recipe: Calling Variadic Functions like &lt;tt&gt;printf&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md38',1,'']]],
  ['limitations_20of_20c_20declarations_31',['1.2 The Limitations of C Declarations',['../md_docs_2signatures.html#autotoc_md165',1,'']]],
  ['linux_20distributions_20deb_20rpm_32',['Linux Distributions (DEB/RPM)',['../md_INSTALL.html#autotoc_md210',1,'']]],
  ['linux_20macos_33',['Method 2: Live Debugging with GDB (Linux/macOS)',['../md_docs_2internals.html#autotoc_md117',1,'']]],
  ['linux_20macos_20bsds_34',['GNU Make (Linux, macOS, BSDs)',['../md_INSTALL.html#autotoc_md198',1,'']]],
  ['live_20debugging_20with_20gdb_20linux_20macos_35',['Method 2: Live Debugging with GDB (Linux/macOS)',['../md_docs_2internals.html#autotoc_md117',1,'']]],
  ['live_20debugging_20with_20windbg_20windows_36',['Method 3: Live Debugging with WinDbg (Windows)',['../md_docs_2internals.html#autotoc_md123',1,'']]],
  ['llvmfuzzertestoneinput_37',['llvmfuzzertestoneinput',['../fuzz__types_8c.html#a91ce7c16e9840492202299da2b451e60',1,'LLVMFuzzerTestOneInput(const uint8_t *data, size_t size):&#160;fuzz_types.c'],['../fuzz__trampoline_8c.html#a91ce7c16e9840492202299da2b451e60',1,'LLVMFuzzerTestOneInput(const uint8_t *data, size_t size):&#160;fuzz_trampoline.c'],['../fuzz__signature_8c.html#a91ce7c16e9840492202299da2b451e60',1,'LLVMFuzzerTestOneInput(const uint8_t *data, size_t size):&#160;fuzz_signature.c']]],
  ['low_20priority_3a_20advanced_20features_20polish_20strong_38',['&lt;strong&gt;Low Priority: Advanced Features &amp; Polish&lt;/strong&gt;',['../md_TODO.html#autotoc_md239',1,'']]]
];
