var searchData=
[
  ['b64_5finput_0',['b64_input',['../structregression__test__case__t.html#a66bf29f7276856355ce26052dd630494',1,'regression_test_case_t']]],
  ['bare_5fhelgrind_5fhandler_1',['bare_helgrind_handler',['../821__threading__bare_8c.html#af448e091d2070a727de081103318b90a',1,'821_threading_bare.c']]],
  ['bare_5fthread_5fworker_2',['bare_thread_worker',['../821__threading__bare_8c.html#ad7ccaadffc3f676752ea58cf2179cdb0',1,'821_threading_bare.c']]],
  ['base_5ftype_3',['base_type',['../group__high__level__api.html#gac70541d021d87d720c38b176fb39e4fc',1,'infix_type_t::base_type'],['../group__high__level__api.html#ga5b5d4e2f45f812ae54b0f1b265d1d54d',1,'infix_type_t::@0::@6::base_type']]],
  ['based_20manual_20api_4',['based manual api',['../md_docs_2internals.html#autotoc_md147',1,'Memory Safety by Default: The Arena-Based Manual API'],['../md_docs_2internals.html#autotoc_md132',1,'Memory Safety by Default: The Arena-Based Manual API']]],
  ['basic_20usage_5',['Basic Usage',['../index.html#usage_sec',1,'']]],
  ['basics_20forward_20calls_6',['Chapter 1: The Basics (Forward Calls)',['../md_docs_2cookbook.html#autotoc_md18',1,'']]],
  ['benefits_20for_20tooling_20and_20mental_20modeling_7',['3.4 Benefits for Tooling and Mental Modeling',['../md_docs_2signatures.html#autotoc_md177',1,'']]],
  ['best_20practice_3a_20caching_20trampolines_8',['Best Practice: Caching Trampolines',['../md_docs_2cookbook.html#autotoc_md71',1,'']]],
  ['best_20practices_20and_20usage_9',['Part 3: Examples, Best Practices, and Usage',['../md_docs_2signatures.html#autotoc_md173',1,'']]],
  ['binding_10',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md81',1,'']]],
  ['bindings_11',['Chapter 9: Building Language Bindings',['../md_docs_2cookbook.html#autotoc_md80',1,'']]],
  ['blockquote_12',['blockquote',['../md_docs_2cookbook.html#autotoc_md42',1,'&lt;/blockquote&gt;'],['../md_docs_2cookbook.html#autotoc_md69',1,'&lt;/blockquote&gt;'],['../md_docs_2cookbook.html#autotoc_md33',1,'&lt;/blockquote&gt;'],['../md_docs_2cookbook.html#autotoc_md23',1,'&lt;/blockquote&gt;']]],
  ['breakpoint_13',['Now, set the breakpoint',['../md_docs_2internals.html#autotoc_md119',1,'']]],
  ['bridge_14',['4. Implementing the Callback Bridge',['../md_docs_2cookbook.html#autotoc_md85',1,'']]],
  ['bsds_15',['GNU Make (Linux, macOS, BSDs)',['../md_INSTALL.html#autotoc_md198',1,'']]],
  ['buffer_16',['buffer',['../structinfix__arena__t.html#a2bafad85c37fba52aaa3dd3311fec20d',1,'infix_arena_t']]],
  ['build_17',['build',['../md_docs_2internals.html#autotoc_md106',1,'A Note on the &quot;Unity&quot; Build'],['../md_docs_2internals.html#autotoc_md145',1,'The Unity Build']]],
  ['build_20systems_18',['Other Build Systems',['..//home/runner/work/infix/infix/README.md#autotoc_md217',1,'']]],
  ['build_20with_20xmake_20recommended_19',['Quick Build with xmake (Recommended)',['..//home/runner/work/infix/infix/README.md#autotoc_md216',1,'']]],
  ['building_20and_20integrating_20',['Building and Integrating',['..//home/runner/work/infix/infix/README.md#autotoc_md215',1,'']]],
  ['building_20and_20integrating_20tt_20infix_20tt_21',['Building and Integrating &lt;tt&gt;infix&lt;/tt&gt;',['../md_INSTALL.html',1,'']]],
  ['building_20language_20bindings_22',['Chapter 9: Building Language Bindings',['../md_docs_2cookbook.html#autotoc_md80',1,'']]],
  ['building_20tt_20infix_20tt_20from_20source_23',['1. Building &lt;tt&gt;infix&lt;/tt&gt; from Source',['../md_INSTALL.html#autotoc_md189',1,'']]],
  ['by_20default_3a_20the_20arena_20based_20manual_20api_24',['by default: the arena based manual api',['../md_docs_2internals.html#autotoc_md147',1,'Memory Safety by Default: The Arena-Based Manual API'],['../md_docs_2internals.html#autotoc_md132',1,'Memory Safety by Default: The Arena-Based Manual API']]],
  ['by_20design_25',['A Note on Memory Safety by Design',['../md_docs_2cookbook.html#autotoc_md78',1,'']]],
  ['by_20reference_26',['Recipe: Large Structs Passed by Reference',['../md_docs_2cookbook.html#autotoc_md27',1,'']]],
  ['by_20reference_20rule_27',['Deep Dive: Windows x64 By-Reference Rule',['../md_docs_2internals.html#autotoc_md111',1,'']]],
  ['by_20value_28',['Recipe: Small Structs Passed by Value',['../md_docs_2cookbook.html#autotoc_md26',1,'']]]
];
