var searchData=
[
  ['f90_20tt_0',['Fortran Code (&lt;tt&gt;libfortran_math.f90&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md49',1,'']]],
  ['features_1',['features',['..//home/runner/work/infix/infix/README.md#autotoc_md195',1,'Features'],['../index.html#features_sec',1,'Key Features']]],
  ['features_20and_20syntax_20handled_2',['Key Features and Syntax Handled',['../signature_8c.html#autotoc_md217',1,'']]],
  ['features_20polish_20strong_3',['&lt;strong&gt;Low Priority: Advanced Features &amp; Polish&lt;/strong&gt;',['../md_TODO.html#autotoc_md231',1,'']]],
  ['ffi_20calls_4',['Recipe: Proving Reentrancy with Nested FFI Calls',['../md_docs_2cookbook.html#autotoc_md39',1,'']]],
  ['ffi_20cookbook_5',['The &lt;tt&gt;infix&lt;/tt&gt; FFI Cookbook',['../md_docs_2cookbook.html',1,'']]],
  ['ffi_20library_6',['ffi library',['../md_CONTRIBUTING.html',1,'Contributing to the infix FFI Library'],['../index.html',1,'Infix FFI Library']]],
  ['ffi_20strong_7',['&lt;strong&gt;Project Roadmap: infix FFI&lt;/strong&gt;',['../md_TODO.html',1,'']]],
  ['ffi_3a_20internals_20documentation_8',['infix FFI: Internals Documentation',['../md_docs_2internals.html',1,'']]],
  ['final_5fmultiply_5fhandler_9',['final_multiply_handler',['../303__advanced_8c.html#a9593dfbf5450b75b6915dd41944df4ad',1,'303_advanced.c']]],
  ['find_5fchar_5fin_5fstring_10',['find_char_in_string',['../201__basic_8c.html#a021325335442088553d22be0cd27cf58',1,'201_basic.c']]],
  ['find_5fpackage_20tt_11',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md_INSTALL.html#autotoc_md185',1,'']]],
  ['fixed_20size_20arrays_12',['Recipe: Working with Fixed-Size Arrays',['../md_docs_2cookbook.html#autotoc_md22',1,'']]],
  ['float_5fcallback_5fhandler_13',['float_callback_handler',['../301__primitives_8c.html#ad80f5c82da708830d5001239d52010db',1,'301_primitives.c']]],
  ['floating_20point_20aggregates_20hfa_14',['Deep Dive: AArch64 Homogeneous Floating-point Aggregates (HFA)',['../md_docs_2internals.html#autotoc_md109',1,'']]],
  ['flow_15',['Trampoline Generation Flow',['../md_docs_2internals.html#autotoc_md100',1,'']]],
  ['for_20cross_20platform_20fuzzing_16',['for cross platform fuzzing',['../md_docs_2internals.html#autotoc_md131',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing'],['../md_docs_2internals.html#autotoc_md146',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing']]],
  ['for_20freed_20trampolines_17',['Guard Pages for Freed Trampolines',['../md_docs_2internals.html#autotoc_md97',1,'']]],
  ['for_20maintainers_18',['3. Packaging &lt;tt&gt;infix&lt;/tt&gt; (For Maintainers)',['../md_INSTALL.html#autotoc_md190',1,'']]],
  ['for_20tt_20qsort_20tt_19',['Recipe: Creating a Stateless Callback for &lt;tt&gt;qsort&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md34',1,'']]],
  ['format_20',['General Format',['../md_docs_2signatures.html#autotoc_md160',1,'']]],
  ['format_20specifiers_21',['Signature Format Specifiers',['../group__signature__specifiers.html',1,'']]],
  ['fortran_22',['Fortran',['../md_docs_2cookbook.html#autotoc_md48',1,'']]],
  ['fortran_20code_20tt_20libfortran_5fmath_20f90_20tt_23',['Fortran Code (&lt;tt&gt;libfortran_math.f90&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md49',1,'']]],
  ['forward_20call_20trampoline_24',['Forward Call Trampoline',['../md_docs_2internals.html#autotoc_md101',1,'']]],
  ['forward_20calls_25',['Chapter 1: The Basics (Forward Calls)',['../md_docs_2cookbook.html#autotoc_md18',1,'']]],
  ['forward_5fvariadic_5fchecker_26',['forward_variadic_checker',['../402__variadic__functions_8c.html#ae984df7920796a4871aeec5b6f167b48',1,'402_variadic_functions.c']]],
  ['foundation_20stability_20strong_27',['&lt;strong&gt;High Priority: Foundation &amp; Stability&lt;/strong&gt;',['../md_TODO.html#autotoc_md229',1,'']]],
  ['four_20pillars_20of_20a_20language_20binding_28',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md78',1,'']]],
  ['free_20prevention_20guard_20pages_29',['2. Use-After-Free Prevention (Guard Pages)',['../md_SECURITY.html#autotoc_md212',1,'']]],
  ['freed_20trampolines_30',['Guard Pages for Freed Trampolines',['../md_docs_2internals.html#autotoc_md97',1,'']]],
  ['from_20a_20function_31',['Recipe: Receiving a Struct from a Function',['../md_docs_2cookbook.html#autotoc_md28',1,'']]],
  ['from_20source_32',['1. Building &lt;tt&gt;infix&lt;/tt&gt; from Source',['../md_INSTALL.html#autotoc_md170',1,'']]],
  ['func_5fptr_5finfo_33',['func_ptr_info',['../group__high__level__api.html#ga99ef1081dea50024de0d00ef8b4c4520',1,'infix_type_t::@0::func_ptr_info'],['../group__high__level__api.html#ga5ade7d61731019aba01d143840ecc392',1,'infix_type_t::func_ptr_info']]],
  ['function_34',['function',['../md_docs_2cookbook.html#autotoc_md19',1,'Recipe: Calling a Simple C Function'],['../md_docs_2cookbook.html#autotoc_md28',1,'Recipe: Receiving a Struct from a Function']]],
  ['function_20pointer_35',['Recipe: Receiving and Calling a Function Pointer',['../md_docs_2cookbook.html#autotoc_md40',1,'']]],
  ['functions_20like_20tt_20printf_20tt_36',['Recipe: Calling Variadic Functions like &lt;tt&gt;printf&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md37',1,'']]],
  ['fuzz_5fabi_2ec_37',['fuzz_abi.c',['../fuzz__abi_8c.html',1,'']]],
  ['fuzz_5fhelpers_2ec_38',['fuzz_helpers.c',['../fuzz__helpers_8c.html',1,'']]],
  ['fuzz_5fhelpers_2eh_39',['fuzz_helpers.h',['../fuzz__helpers_8h.html',1,'']]],
  ['fuzz_5fregression_5fhelpers_2eh_40',['fuzz_regression_helpers.h',['../fuzz__regression__helpers_8h.html',1,'']]],
  ['fuzz_5fsignature_2ec_41',['fuzz_signature.c',['../fuzz__signature_8c.html',1,'']]],
  ['fuzz_5ftrampoline_2ec_42',['fuzz_trampoline.c',['../fuzz__trampoline_8c.html',1,'']]],
  ['fuzz_5ftypes_2ec_43',['fuzz_types.c',['../fuzz__types_8c.html',1,'']]],
  ['fuzzer_5finput_44',['fuzzer_input',['../structfuzzer__input.html',1,'']]],
  ['fuzzer_5ftarget_5ft_45',['fuzzer_target_t',['../850__regression__cases_8c.html#a069f203eb4bd59c4b6e646ea3cef8c26',1,'850_regression_cases.c']]],
  ['fuzzing_46',['fuzzing',['../md_SECURITY.html#autotoc_md215',1,'5. Continuous Security Validation (Fuzzing)'],['../md_docs_2internals.html#autotoc_md146',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing'],['../md_docs_2internals.html#autotoc_md131',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing']]],
  ['fuzzing_20targets_47',['Fuzzing Targets',['../fuzz__signature_8c.html#autotoc_md165',1,'']]]
];
