var searchData=
[
  ['underlying_5ftype_0',['underlying_type',['../group__high__level__api.html#gaeeeeac278209a4aa5f3024b196d89292',1,'infix_type_t::underlying_type'],['../group__high__level__api.html#ga8c923a189eb6700fd770f8f815aeef1e',1,'infix_type_t::@0::@5::underlying_type']]],
  ['unions_1',['Recipe: Working with Unions',['../md_docs_2cookbook.html#autotoc_md30',1,'']]],
  ['unity_20build_2',['unity build',['../md_docs_2internals.html#autotoc_md106',1,'A Note on the &quot;Unity&quot; Build'],['../md_docs_2internals.html#autotoc_md145',1,'The Unity Build']]],
  ['universal_20context_3',['universal context',['../md_docs_2internals.html#autotoc_md148',1,'Callbacks: The Power of the Universal Context'],['../md_docs_2internals.html#autotoc_md133',1,'Callbacks: The Power of the Universal Context']]],
  ['universal_20principle_3a_20the_20c_20abi_4',['The Universal Principle: The C ABI',['../md_docs_2cookbook.html#autotoc_md44',1,'']]],
  ['unreleased_5',['[Unreleased]',['../md_CHANGELOG.html#autotoc_md1',1,'']]],
  ['usage_6',['usage',['../index.html#usage_sec',1,'Basic Usage'],['../md_docs_2signatures.html#autotoc_md173',1,'Part 3: Examples, Best Practices, and Usage']]],
  ['use_7',['3.2 Architectural Pattern: Define and Use',['../md_docs_2signatures.html#autotoc_md175',1,'']]],
  ['use_20after_20free_20prevention_20guard_20pages_8',['2. Use-After-Free Prevention (Guard Pages)',['../md_SECURITY.html#autotoc_md231',1,'']]],
  ['user_5fcallback_5ffn_9',['user_callback_fn',['../structinfix__reverse__t.html#a14fd69f1efa6fedb2a879ae3e61cadaf',1,'infix_reverse_t']]],
  ['user_5fdata_10',['user_data',['../structinfix__reverse__t.html#a108353aa68bb87b6cbe6d28fcb5318e1',1,'infix_reverse_t']]],
  ['userprofile_11',['UserProfile',['../structUserProfile.html',1,'']]],
  ['using_20cmake_12',['Using CMake',['../md_INSTALL.html#autotoc_md192',1,'']]],
  ['using_20cmake_20with_20tt_20find_5fpackage_20tt_13',['Using CMake with &lt;tt&gt;find_package&lt;/tt&gt;',['../md_INSTALL.html#autotoc_md204',1,'']]],
  ['using_20in_20visual_20studio_20code_14',['Using in Visual Studio Code',['../md_INSTALL.html#autotoc_md207',1,'']]],
  ['using_20makefiles_15',['Using Makefiles',['../md_INSTALL.html#autotoc_md197',1,'']]],
  ['using_20perl_16',['Using Perl',['../md_INSTALL.html#autotoc_md191',1,'']]],
  ['using_20pkg_20config_17',['Using pkg-config',['../md_INSTALL.html#autotoc_md205',1,'']]],
  ['using_20xmake_18',['Using xmake',['../md_INSTALL.html#autotoc_md206',1,'']]],
  ['using_20xmake_20recommended_19',['Using xmake (Recommended)',['../md_INSTALL.html#autotoc_md190',1,'']]],
  ['utility_2ec_20',['utility.c',['../utility_8c.html',1,'']]],
  ['utility_2eh_21',['utility.h',['../utility_8h.html',1,'']]]
];
