var searchData=
[
  ['d_20code_20tt_20libd_5fmath_20d_20tt_0',['D Code (&lt;tt&gt;libd_math.d&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['d_20dlang_1',['D (dlang)',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['d_20tt_2',['D Code (&lt;tt&gt;libd_math.d&lt;/tt&gt;)',['../md_docs_2cookbook.html#autotoc_md62',1,'']]],
  ['data_20marshalling_3',['Powerful Introspection for Dynamic Data Marshalling',['..//home/runner/work/infix/infix/README.md#autotoc_md221',1,'']]],
  ['data_20structures_4',['Chapter 2: Handling Complex Data Structures',['../md_docs_2cookbook.html#autotoc_md24',1,'']]],
  ['data_20types_5',['4.5 Rationale for Advanced Data Types',['../md_docs_2signatures.html#autotoc_md183',1,'']]],
  ['deb_20rpm_6',['Linux Distributions (DEB/RPM)',['../md_INSTALL.html#autotoc_md211',1,'']]],
  ['debugging_20guide_7',['The Debugging Guide',['../md_docs_2internals.html#autotoc_md114',1,'']]],
  ['debugging_20with_20gdb_20linux_20macos_8',['Method 2: Live Debugging with GDB (Linux/macOS)',['../md_docs_2internals.html#autotoc_md117',1,'']]],
  ['debugging_20with_20windbg_20windows_9',['Method 3: Live Debugging with WinDbg (Windows)',['../md_docs_2internals.html#autotoc_md123',1,'']]],
  ['decisions_10',['Design Philosophy: Key Architectural Decisions',['../md_docs_2internals.html#autotoc_md144',1,'']]],
  ['declarations_11',['1.2 The Limitations of C Declarations',['../md_docs_2signatures.html#autotoc_md165',1,'']]],
  ['deep_20dive_3a_20aarch64_20homogeneous_20floating_20point_20aggregates_20hfa_12',['Deep Dive: AArch64 Homogeneous Floating-point Aggregates (HFA)',['../md_docs_2internals.html#autotoc_md112',1,'']]],
  ['deep_20dive_3a_20system_20v_20amd64_20aggregate_20classification_13',['Deep Dive: System V AMD64 Aggregate Classification',['../md_docs_2internals.html#autotoc_md110',1,'']]],
  ['deep_20dive_3a_20windows_20x64_20by_20reference_20rule_14',['Deep Dive: Windows x64 By-Reference Rule',['../md_docs_2internals.html#autotoc_md111',1,'']]],
  ['default_3a_20the_20arena_20based_20manual_20api_15',['default: the arena based manual api',['../md_docs_2internals.html#autotoc_md147',1,'Memory Safety by Default: The Arena-Based Manual API'],['../md_docs_2internals.html#autotoc_md132',1,'Memory Safety by Default: The Arena-Based Manual API']]],
  ['define_20and_20use_16',['3.2 Architectural Pattern: Define and Use',['../md_docs_2signatures.html#autotoc_md175',1,'']]],
  ['define_5fconsume_5ft_17',['DEFINE_CONSUME_T',['../fuzz__helpers_8h.html#a0a3095b072722fae3f76a6d936debfc6',1,'fuzz_helpers.h']]],
  ['definitions_18',['Common Windows Type Definitions',['../md_docs_2internals.html#autotoc_md127',1,'']]],
  ['depth_19',['depth',['../structparser__state.html#aa6acb3fad5e4ab8d8a0a656402ff13a4',1,'parser_state']]],
  ['design_20',['A Note on Memory Safety by Design',['../md_docs_2cookbook.html#autotoc_md78',1,'']]],
  ['design_20philosophy_21',['design philosophy',['../md_docs_2internals.html#autotoc_md129',1,'Core Design Philosophy'],['../md_docs_2internals.html#autotoc_md89',1,'Core Design Philosophy']]],
  ['design_20philosophy_3a_20a_20stable_20public_20api_22',['Design Philosophy: A Stable Public API',['../md_docs_2internals.html#autotoc_md136',1,'']]],
  ['design_20philosophy_3a_20key_20architectural_20decisions_23',['Design Philosophy: Key Architectural Decisions',['../md_docs_2internals.html#autotoc_md144',1,'']]],
  ['design_20philosophy_3a_20the_20jit_20compiler_20vs_20the_20call_20vm_24',['Core Design Philosophy: The JIT Compiler vs. The Call VM',['../md_docs_2internals.html#autotoc_md139',1,'']]],
  ['design_20rationale_25',['Part 4: Technical Specification and Design Rationale',['../md_docs_2signatures.html#autotoc_md178',1,'']]],
  ['design_20rationale_3a_20why_20this_20syntax_26',['4.3 Design Rationale: Why This Syntax?',['../md_docs_2signatures.html#autotoc_md181',1,'']]],
  ['detection_20tt_20infix_20h_20tt_27',['Step 1: Platform Detection (&lt;tt&gt;infix.h&lt;/tt&gt;)',['../md_docs_2porting.html#autotoc_md155',1,'']]],
  ['differences_28',['Pitfall: Struct Packing Differences',['../md_docs_2cookbook.html#autotoc_md77',1,'']]],
  ['dispatch_3a_20v_20tables_20for_20cross_20platform_20fuzzing_29',['dispatch: v tables for cross platform fuzzing',['../md_docs_2internals.html#autotoc_md134',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing'],['../md_docs_2internals.html#autotoc_md149',1,'ABI Dispatch: V-Tables for Cross-Platform Fuzzing']]],
  ['distributions_20deb_20rpm_30',['Linux Distributions (DEB/RPM)',['../md_INSTALL.html#autotoc_md211',1,'']]],
  ['dive_3a_20aarch64_20homogeneous_20floating_20point_20aggregates_20hfa_31',['Deep Dive: AArch64 Homogeneous Floating-point Aggregates (HFA)',['../md_docs_2internals.html#autotoc_md112',1,'']]],
  ['dive_3a_20system_20v_20amd64_20aggregate_20classification_32',['Deep Dive: System V AMD64 Aggregate Classification',['../md_docs_2internals.html#autotoc_md110',1,'']]],
  ['dive_3a_20windows_20x64_20by_20reference_20rule_33',['Deep Dive: Windows x64 By-Reference Rule',['../md_docs_2internals.html#autotoc_md111',1,'']]],
  ['dlang_34',['D (dlang)',['../md_docs_2cookbook.html#autotoc_md61',1,'']]],
  ['do_5fnothing_35',['do_nothing',['../002__simple__calls_8c.html#a15196b401013e8f2274566f6432b4ba4',1,'002_simple_calls.c']]],
  ['documentation_36',['documentation',['../md_docs_2internals.html#autotoc_md125',1,'External ABI Documentation'],['../md_docs_2internals.html',1,'infix FFI: Internals Documentation']]],
  ['documentation_20license_37',['Documentation License',['..//home/runner/work/infix/infix/README.md#autotoc_md227',1,'']]],
  ['double_5ftap_2eh_38',['double_tap.h',['../double__tap_8h.html',1,'']]],
  ['dynamic_20data_20marshalling_39',['Powerful Introspection for Dynamic Data Marshalling',['..//home/runner/work/infix/infix/README.md#autotoc_md221',1,'']]],
  ['dynamic_20struct_20marshalling_20with_20the_20signature_20parser_40',['Recipe: Dynamic Struct Marshalling with the Signature Parser',['../md_docs_2cookbook.html#autotoc_md25',1,'']]],
  ['dyncall_20tt_41',['The Alternative: The Call VM / Interpreter Model (e.g., &lt;tt&gt;dyncall&lt;/tt&gt;)',['../md_docs_2internals.html#autotoc_md140',1,'']]]
];
