var searchData=
[
  ['object_20lifetimes_0',['3. Managing Memory &amp; Object Lifetimes',['../md_docs_2cookbook.html#autotoc_md84',1,'']]],
  ['of_20a_20language_20binding_1',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md81',1,'']]],
  ['of_20a_20pointer_20in_20tt_20args_20tt_2',['Mistake: Passing a Value Instead of a Pointer in &lt;tt&gt;args[]&lt;/tt&gt;',['../md_docs_2cookbook.html#autotoc_md74',1,'']]],
  ['of_20c_20declarations_3',['1.2 The Limitations of C Declarations',['../md_docs_2signatures.html#autotoc_md165',1,'']]],
  ['of_20callbacks_20reverse_20calls_4',['Chapter 3: The Power of Callbacks (Reverse Calls)',['../md_docs_2cookbook.html#autotoc_md34',1,'']]],
  ['of_20conduct_5',['of conduct',['../md_CONTRIBUTING.html#autotoc_md11',1,'Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Contributor Code of Conduct']]],
  ['of_20contents_6',['Table of Contents',['../md_docs_2cookbook.html#autotoc_md16',1,'']]],
  ['of_20interoperability_7',['1.1 The Challenge of Interoperability',['../md_docs_2signatures.html#autotoc_md164',1,'']]],
  ['of_20the_20universal_20context_8',['of the universal context',['../md_docs_2internals.html#autotoc_md148',1,'Callbacks: The Power of the Universal Context'],['../md_docs_2internals.html#autotoc_md133',1,'Callbacks: The Power of the Universal Context']]],
  ['offset_9',['offset',['../group__high__level__api.html#gabc9fb3780626694111f4c8c74700a9b9',1,'infix_struct_member_t']]],
  ['on_20memory_20safety_20by_20design_10',['A Note on Memory Safety by Design',['../md_docs_2cookbook.html#autotoc_md78',1,'']]],
  ['on_20the_20unity_20build_11',['A Note on the &quot;Unity&quot; Build',['../md_docs_2internals.html#autotoc_md106',1,'']]],
  ['only_20callback_20contexts_12',['Read-Only Callback Contexts',['../md_docs_2internals.html#autotoc_md101',1,'']]],
  ['only_20context_20hardening_13',['3. Read-Only Context Hardening',['../md_SECURITY.html#autotoc_md232',1,'']]],
  ['opaque_20pointers_20incomplete_20types_14',['Recipe: Working with Opaque Pointers (Incomplete Types)',['../md_docs_2cookbook.html#autotoc_md21',1,'']]],
  ['optimization_20strong_15',['&lt;strong&gt;Medium Priority: Expansion &amp; Optimization&lt;/strong&gt;',['../md_TODO.html#autotoc_md238',1,'']]],
  ['other_20build_20systems_16',['Other Build Systems',['..//home/runner/work/infix/infix/README.md#autotoc_md217',1,'']]],
  ['other_20languages_17',['Chapter 5: Interoperability with Other Languages',['../md_docs_2cookbook.html#autotoc_md43',1,'']]],
  ['other_20systems_18',['4.4 Comparison with Other Systems',['../md_docs_2signatures.html#autotoc_md182',1,'']]],
  ['our_20pledge_19',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md4',1,'']]],
  ['our_20responsibilities_20',['Our Responsibilities',['../md_CODE__OF__CONDUCT.html#autotoc_md6',1,'']]],
  ['our_20solution_3a_20a_20human_20first_20signature_20system_21',['1.3 Our Solution: A Human-First Signature System',['../md_docs_2signatures.html#autotoc_md166',1,'']]],
  ['our_20standards_22',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md5',1,'']]],
  ['overflows_23',['4. API Hardening Against Integer Overflows',['../md_SECURITY.html#autotoc_md233',1,'']]],
  ['overview_24',['overview',['..//home/runner/work/infix/infix/README.md#autotoc_md218',1,'API Overview'],['../md_docs_2internals.html#autotoc_md91',1,'Architectural Overview'],['../md_docs_2internals.html#autotoc_md109',1,'Comparative Overview']]]
];
