var searchData=
[
  ['b64_5finput_0',['b64_input',['../structregression__test__case__t.html#a66bf29f7276856355ce26052dd630494',1,'regression_test_case_t']]],
  ['bare_5fhelgrind_5fhandler_1',['bare_helgrind_handler',['../821__threading__bare_8c.html#af448e091d2070a727de081103318b90a',1,'821_threading_bare.c']]],
  ['bare_5fthread_5fworker_2',['bare_thread_worker',['../821__threading__bare_8c.html#ad7ccaadffc3f676752ea58cf2179cdb0',1,'821_threading_bare.c']]],
  ['based_20manual_20api_3',['based manual api',['../md_docs_2internals.html#autotoc_md144',1,'Memory Safety by Default: The Arena-Based Manual API'],['../md_docs_2internals.html#autotoc_md129',1,'Memory Safety by Default: The Arena-Based Manual API']]],
  ['basic_20usage_4',['Basic Usage',['../index.html#usage_sec',1,'']]],
  ['basics_20forward_20calls_5',['Chapter 1: The Basics (Forward Calls)',['../md_docs_2cookbook.html#autotoc_md18',1,'']]],
  ['best_20practice_3a_20caching_20trampolines_6',['Best Practice: Caching Trampolines',['../md_docs_2cookbook.html#autotoc_md70',1,'']]],
  ['binding_7',['The Four Pillars of a Language Binding',['../md_docs_2cookbook.html#autotoc_md78',1,'']]],
  ['bindings_8',['Chapter 9: Building Language Bindings',['../md_docs_2cookbook.html#autotoc_md77',1,'']]],
  ['blockquote_9',['blockquote',['../md_docs_2cookbook.html#autotoc_md32',1,'&lt;/blockquote&gt;'],['../md_docs_2cookbook.html#autotoc_md68',1,'&lt;/blockquote&gt;'],['../md_docs_2cookbook.html#autotoc_md41',1,'&lt;/blockquote&gt;'],['../md_docs_2cookbook.html#autotoc_md23',1,'&lt;/blockquote&gt;']]],
  ['breakpoint_10',['Now, set the breakpoint',['../md_docs_2internals.html#autotoc_md116',1,'']]],
  ['bridge_11',['4. Implementing the Callback Bridge',['../md_docs_2cookbook.html#autotoc_md82',1,'']]],
  ['bsds_12',['GNU Make (Linux, macOS, BSDs)',['../md_INSTALL.html#autotoc_md179',1,'']]],
  ['buffer_13',['buffer',['../structinfix__arena__t.html#a2bafad85c37fba52aaa3dd3311fec20d',1,'infix_arena_t']]],
  ['build_14',['build',['../md_docs_2internals.html#autotoc_md103',1,'A Note on the &quot;Unity&quot; Build'],['../md_docs_2internals.html#autotoc_md142',1,'The Unity Build']]],
  ['build_20systems_15',['Other Build Systems',['..//home/runner/work/infix/infix/README.md#autotoc_md198',1,'']]],
  ['build_20with_20xmake_20recommended_16',['Quick Build with xmake (Recommended)',['..//home/runner/work/infix/infix/README.md#autotoc_md197',1,'']]],
  ['building_20and_20integrating_17',['Building and Integrating',['..//home/runner/work/infix/infix/README.md#autotoc_md196',1,'']]],
  ['building_20and_20integrating_20tt_20infix_20tt_18',['Building and Integrating &lt;tt&gt;infix&lt;/tt&gt;',['../md_INSTALL.html',1,'']]],
  ['building_20language_20bindings_19',['Chapter 9: Building Language Bindings',['../md_docs_2cookbook.html#autotoc_md77',1,'']]],
  ['building_20tt_20infix_20tt_20from_20source_20',['1. Building &lt;tt&gt;infix&lt;/tt&gt; from Source',['../md_INSTALL.html#autotoc_md170',1,'']]],
  ['by_20default_3a_20the_20arena_20based_20manual_20api_21',['by default: the arena based manual api',['../md_docs_2internals.html#autotoc_md129',1,'Memory Safety by Default: The Arena-Based Manual API'],['../md_docs_2internals.html#autotoc_md144',1,'Memory Safety by Default: The Arena-Based Manual API']]],
  ['by_20design_22',['A Note on Memory Safety by Design',['../md_docs_2cookbook.html#autotoc_md75',1,'']]],
  ['by_20reference_23',['Recipe: Large Structs Passed by Reference',['../md_docs_2cookbook.html#autotoc_md27',1,'']]],
  ['by_20reference_20rule_24',['Deep Dive: Windows x64 By-Reference Rule',['../md_docs_2internals.html#autotoc_md108',1,'']]],
  ['by_20value_25',['Recipe: Small Structs Passed by Value',['../md_docs_2cookbook.html#autotoc_md26',1,'']]]
];
